// Hebrew idioms data for Advanced Conjugation game mode.
// Each entry exposes a normalized shape used by advConj functions in app.js:
//   present_tense  — alias for conjugations.present
//   past_tense     — alias for conjugations.past
//   future_tense   — alias for conjugations.future
//   english_meaning — alias for english
const HEBREW_IDIOMS = (function () {
  const raw = [
  {
    "id": "shaga",
    "level": 1,
    "infinitive": "לשגע מישהו",
    "english": "to drive someone crazy",
    "verb": "לשגע",
    "root": "ש.ג.ע",
    "binyan": "piel",
    "object_type": "direct",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩",
    "example": "אתה משגע אותי",
    "negated": false,
    "literal_sg": "{s} drives {o} crazy",
    "literal_pl": "{s} drive {o} crazy",
    "literal_past": "{s} drove {o} crazy",
    "literal_future": "{s} will drive {o} crazy",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "משגע", "fsg": "משגעת", "mpl": "משגעים", "fpl": "משגעות" },
      "past":    { "msg": "שיגע", "fsg": "שיגעה", "mpl": "שיגעו", "fpl": "שיגעו" },
      "future":  { "msg": "ישגע", "fsg": "תשגע", "mpl": "ישגעו", "fpl": "ישגעו" }
    }
  },
  {
    "id": "itzben",
    "level": 1,
    "infinitive": "לעצבן מישהו",
    "english": "to annoy someone",
    "verb": "לעצבן",
    "root": "ע.צ.ב.נ",
    "binyan": "piel",
    "object_type": "direct",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩",
    "example": "אתה מעצבן אותי",
    "negated": false,
    "literal_sg": "{s} annoys {o}",
    "literal_pl": "{s} annoy {o}",
    "literal_past": "{s} annoyed {o}",
    "literal_future": "{s} will annoy {o}",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "מעצבן", "fsg": "מעצבנת", "mpl": "מעצבנים", "fpl": "מעצבנות" },
      "past":    { "msg": "עיצבן", "fsg": "עיצבנה", "mpl": "עיצבנו", "fpl": "עיצבנו" },
      "future":  { "msg": "יעצבן", "fsg": "תעצבן", "mpl": "יעצבנו", "fpl": "יעצבנו" }
    }
  },
  {
    "id": "hidlik",
    "level": 1,
    "infinitive": "להדליק מישהו",
    "english": "to excite / turn someone on",
    "verb": "להדליק",
    "root": "ד.ל.ק",
    "binyan": "hifil",
    "object_type": "direct",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩",
    "example": "אתה מדליק אותי",
    "negated": false,
    "literal_sg": "{s} lights {o} up",
    "literal_pl": "{s} light {o} up",
    "literal_past": "{s} lit {o} up",
    "literal_future": "{s} will light {o} up",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "מדליק", "fsg": "מדליקה", "mpl": "מדליקים", "fpl": "מדליקות" },
      "past":    { "msg": "הדליק", "fsg": "הדליקה", "mpl": "הדליקו", "fpl": "הדליקו" },
      "future":  { "msg": "ידליק", "fsg": "תדליק", "mpl": "ידליקו", "fpl": "ידליקו" }
    }
  },
  {
    "id": "hitrif",
    "level": 1,
    "infinitive": "להטריף מישהו",
    "english": "to drive someone insane",
    "verb": "להטריף",
    "root": "ט.ר.פ",
    "binyan": "hifil",
    "object_type": "direct",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩",
    "example": "אתה מטריף אותי",
    "negated": false,
    "literal_sg": "{s} drives {o} insane",
    "literal_pl": "{s} drive {o} insane",
    "literal_past": "{s} drove {o} insane",
    "literal_future": "{s} will drive {o} insane",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "מטריף", "fsg": "מטריפה", "mpl": "מטריפים", "fpl": "מטריפות" },
      "past":    { "msg": "הטריף", "fsg": "הטריפה", "mpl": "הטריפו", "fpl": "הטריפו" },
      "future":  { "msg": "יטריף", "fsg": "תטריף", "mpl": "יטריפו", "fpl": "יטריפו" }
    }
  },
  {
    "id": "kara",
    "level": 1,
    "infinitive": "לקרוע מישהו",
    "english": "(to kill/send someone [funny])",
    "verb": "לקרוע",
    "root": "ק.ר.ע",
    "binyan": "qal",
    "object_type": "direct",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩",
    "example": "הוא קורע אותי",
    "negated": false,
    "literal_sg": "{s} tears {o}",
    "literal_pl": "{s} tear {o}",
    "literal_past": "{s} tore {o}",
    "literal_future": "{s} will tear {o}",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "קורע", "fsg": "קורעת", "mpl": "קורעים", "fpl": "קורעות" },
      "past":    { "msg": "קרע", "fsg": "קרעה", "mpl": "קרעו", "fpl": "קרעו" },
      "future":  { "msg": "יקרע", "fsg": "תקרע", "mpl": "יקרעו", "fpl": "יקרעו" }
    }
  },
  {
    "id": "haalat_sif",
    "level": 2,
    "infinitive": "להעלות למישהו את הסעיף",
    "english": "to drive someone up the wall",
    "verb": "להעלות",
    "root": "ע.ל.ה",
    "binyan": "hifil",
    "object_type": "l_dative",
    "fixed_object": "את הסעיף",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את הסעיף",
    "example": "אתה מעלה לי את הסעיף",
    "negated": false,
    "literal_sg": "{s} raises {p} paragraph",
    "literal_pl": "{s} raise {p} paragraph",
    "literal_past": "{s} raised {p} paragraph",
    "literal_future": "{s} will raise {p} paragraph",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "מעלה", "fsg": "מעלה", "mpl": "מעלים", "fpl": "מעלות" },
      "past":    { "msg": "העלה", "fsg": "העלתה", "mpl": "העלו", "fpl": "העלו" },
      "future":  { "msg": "יעלה", "fsg": "תעלה", "mpl": "יעלו", "fpl": "יעלו" }
    }
  },
  {
    "id": "horadat_hesheq",
    "level": 2,
    "infinitive": "להוריד למישהו את החשק",
    "english": "to kill someone's motivation",
    "verb": "להוריד",
    "root": "י.ר.ד",
    "binyan": "hifil",
    "object_type": "l_dative",
    "fixed_object": "את החשק",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את החשק",
    "example": "אתה מוריד לי את החשק",
    "negated": false,
    "literal_sg": "{s} brings down {p} desire",
    "literal_pl": "{s} bring down {p} desire",
    "literal_past": "{s} brought down {p} desire",
    "literal_future": "{s} will bring down {p} desire",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "מוריד", "fsg": "מורידה", "mpl": "מורידים", "fpl": "מורידות" },
      "past":    { "msg": "הוריד", "fsg": "הורידה", "mpl": "הורידו", "fpl": "הורידו" },
      "future":  { "msg": "יוריד", "fsg": "תוריד", "mpl": "יורידו", "fpl": "יורידו" }
    }
  },
  {
    "id": "hotzaat_mitz",
    "level": 2,
    "infinitive": "להוציא למישהו את המיץ",
    "english": "to exhaust / wear someone out",
    "verb": "להוציא",
    "root": "י.צ.א",
    "binyan": "hifil",
    "object_type": "l_dative",
    "fixed_object": "את המיץ",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את המיץ",
    "example": "אתה מוציא לי את המיץ",
    "negated": false,
    "literal_sg": "{s} takes out {p} juice",
    "literal_pl": "{s} take out {p} juice",
    "literal_past": "{s} took out {p} juice",
    "literal_future": "{s} will take out {p} juice",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "מוציא", "fsg": "מוציאה", "mpl": "מוציאים", "fpl": "מוציאות" },
      "past":    { "msg": "הוציא", "fsg": "הוציאה", "mpl": "הוציאו", "fpl": "הוציאו" },
      "future":  { "msg": "יוציא", "fsg": "תוציא", "mpl": "יוציאו", "fpl": "יוציאו" }
    }
  },
  {
    "id": "shvira_lev",
    "level": 2,
    "infinitive": "לשבור למישהו את הלב",
    "english": "to break someone's heart",
    "verb": "לשבור",
    "root": "ש.ב.ר",
    "binyan": "qal",
    "object_type": "l_dative",
    "fixed_object": "את הלב",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את הלב",
    "example": "אתה שובר לי את הלב",
    "negated": false,
    "literal_sg": "{s} breaks {p} heart",
    "literal_pl": "{s} break {p} heart",
    "literal_past": "{s} broke {p} heart",
    "literal_future": "{s} will break {p} heart",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "שובר", "fsg": "שוברת", "mpl": "שוברים", "fpl": "שוברות" },
      "past":    { "msg": "שבר", "fsg": "שברה", "mpl": "שברו", "fpl": "שברו" },
      "future":  { "msg": "ישבור", "fsg": "תשבור", "mpl": "ישברו", "fpl": "ישברו" }
    }
  },
  {
    "id": "asiya_hayim",
    "level": 2,
    "infinitive": "לעשות למישהו את החיים קשים",
    "english": "to make someone's life difficult",
    "verb": "לעשות",
    "root": "ע.ש.ה",
    "binyan": "qal",
    "object_type": "l_dative",
    "fixed_object": "את החיים קשים",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את החיים קשים",
    "example": "אתה עושה לי את החיים קשים",
    "negated": false,
    "literal_sg": "{s} makes {p} life difficult",
    "literal_pl": "{s} make {p} life difficult",
    "literal_past": "{s} made {p} life difficult",
    "literal_future": "{s} will make {p} life difficult",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "עושה", "fsg": "עושה", "mpl": "עושים", "fpl": "עושות" },
      "past":    { "msg": "עשה", "fsg": "עשתה", "mpl": "עשו", "fpl": "עשו" },
      "future":  { "msg": "יעשה", "fsg": "תעשה", "mpl": "יעשו", "fpl": "יעשו" }
    }
  },
  {
    "id": "hfalat_asiman",
    "level": 2,
    "infinitive": "להפיל למישהו את האסימון",
    "english": "(to make it click/make sense for someone)",
    "verb": "להפיל",
    "root": "נ.פ.ל",
    "binyan": "hifil",
    "object_type": "l_dative",
    "fixed_object": "את האסימון",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את האסימון",
    "example": "אתה מפיל לי את האסימון",
    "negated": false,
    "literal_sg": "{s} drops {p} token",
    "literal_pl": "{s} drop {p} token",
    "literal_past": "{s} dropped {p} token",
    "literal_future": "{s} will drop {p} token",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "מפיל", "fsg": "מפילה", "mpl": "מפילים", "fpl": "מפילות" },
      "past":    { "msg": "הפיל", "fsg": "הפילה", "mpl": "הפילו", "fpl": "הפילו" },
      "future":  { "msg": "יפיל", "fsg": "תפיל", "mpl": "יפילו", "fpl": "יפילו" }
    }
  },
  {
    "id": "ptihat_einayim",
    "level": 2,
    "infinitive": "לפתוח למישהו את העיניים",
    "english": "to open someone's eyes",
    "verb": "לפתוח",
    "root": "פ.ת.ח",
    "binyan": "qal",
    "object_type": "l_dative",
    "fixed_object": "את העיניים",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את העיניים",
    "example": "אתה פותח לי את העיניים",
    "negated": false,
    "literal_sg": "{s} opens {p} eyes",
    "literal_pl": "{s} open {p} eyes",
    "literal_past": "{s} opened {p} eyes",
    "literal_future": "{s} will open {p} eyes",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "פותח", "fsg": "פותחת", "mpl": "פותחים", "fpl": "פותחות" },
      "past":    { "msg": "פתח", "fsg": "פתחה", "mpl": "פתחו", "fpl": "פתחו" },
      "future":  { "msg": "יפתח", "fsg": "תפתח", "mpl": "יפתחו", "fpl": "יפתחו" }
    }
  },
  {
    "id": "yeshiva_neshama",
    "level": 2,
    "infinitive": "לשבת למישהו על הנשמה",
    "english": "to suffocate / pressure someone",
    "verb": "לשבת",
    "root": "י.ש.ב",
    "binyan": "qal",
    "object_type": "l_dative",
    "fixed_object": "על הנשמה",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ על הנשמה",
    "example": "אתה יושב לי על הנשמה",
    "negated": false,
    "literal_sg": "{s} sits on {p} soul",
    "literal_pl": "{s} sit on {p} soul",
    "literal_past": "{s} sat on {p} soul",
    "literal_future": "{s} will sit on {p} soul",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "יושב", "fsg": "יושבת", "mpl": "יושבים", "fpl": "יושבות" },
      "past":    { "msg": "ישב", "fsg": "ישבה", "mpl": "ישבו", "fpl": "ישבו" },
      "future":  { "msg": "יישב", "fsg": "תישב", "mpl": "יישבו", "fpl": "יישבו" }
    }
  },
  {
    "id": "yerida_gav",
    "level": 2,
    "infinitive": "לרדת למישהו מהגב",
    "english": "to get off someone's back",
    "verb": "לרדת",
    "root": "י.ר.ד",
    "binyan": "qal",
    "object_type": "l_dative",
    "fixed_object": "מהגב",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ מהגב",
    "example": "אתה יורד לי מהגב",
    "negated": false,
    "literal_sg": "{s} gets off {p} back",
    "literal_pl": "{s} get off {p} back",
    "literal_past": "{s} got off {p} back",
    "literal_future": "{s} will get off {p} back",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "יורד", "fsg": "יורדת", "mpl": "יורדים", "fpl": "יורדות" },
      "past":    { "msg": "ירד", "fsg": "ירדה", "mpl": "ירדו", "fpl": "ירדו" },
      "future":  { "msg": "יירד", "fsg": "תירד", "mpl": "יירדו", "fpl": "יירדו" }
    }
  },
  {
    "id": "amida_derekh",
    "level": 2,
    "infinitive": "לעמוד למישהו בדרך",
    "english": "to stand in someone's way",
    "verb": "לעמוד",
    "root": "ע.מ.ד",
    "binyan": "qal",
    "object_type": "l_dative",
    "fixed_object": "בדרך",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ בדרך",
    "example": "אתה עומד לי בדרך",
    "negated": false,
    "literal_sg": "{s} stands in {p} way",
    "literal_pl": "{s} stand in {p} way",
    "literal_past": "{s} stood in {p} way",
    "literal_future": "{s} will stand in {p} way",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "עומד", "fsg": "עומדת", "mpl": "עומדים", "fpl": "עומדות" },
      "past":    { "msg": "עמד", "fsg": "עמדה", "mpl": "עמדו", "fpl": "עמדו" },
      "future":  { "msg": "יעמוד", "fsg": "תעמוד", "mpl": "יעמדו", "fpl": "יעמדו" }
    }
  },
  {
    "id": "khnisa_rosh",
    "level": 2,
    "infinitive": "להיכנס למישהו לראש",
    "english": "to get inside someone's head",
    "verb": "להיכנס",
    "root": "כ.נ.ס",
    "binyan": "nifal",
    "object_type": "l_dative",
    "fixed_object": "לראש",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ לראש",
    "example": "אתה נכנס לי לראש",
    "negated": false,
    "literal_sg": "{s} enters {p} head",
    "literal_pl": "{s} enter {p} head",
    "literal_past": "{s} entered {p} head",
    "literal_future": "{s} will enter {p} head",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "נכנס", "fsg": "נכנסת", "mpl": "נכנסים", "fpl": "נכנסות" },
      "past":    { "msg": "נכנס", "fsg": "נכנסה", "mpl": "נכנסו", "fpl": "נכנסו" },
      "future":  { "msg": "ייכנס", "fsg": "תיכנס", "mpl": "ייכנסו", "fpl": "ייכנסו" }
    }
  },
  {
    "id": "lo_yatza_rosh",
    "level": 2,
    "infinitive": "לא לצאת למישהו מהראש",
    "english": "to not leave someone's head",
    "verb": "לצאת",
    "root": "י.צ.א",
    "binyan": "qal",
    "object_type": "l_dative",
    "fixed_object": "מהראש",
    "template": "לא ⟨VERB⟩ ⟨L_OBJ⟩ מהראש",
    "example": "אתה לא יוצא לי מהראש",
    "negated": true,
    "literal_sg": "{s} doesn't leave {p} head",
    "literal_pl": "{s} don't leave {p} head",
    "literal_past": "{s} didn't leave {p} head",
    "literal_future": "{s} won't leave {p} head",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "יוצא", "fsg": "יוצאת", "mpl": "יוצאים", "fpl": "יוצאות" },
      "past":    { "msg": "יצא", "fsg": "יצאה", "mpl": "יצאו", "fpl": "יצאו" },
      "future":  { "msg": "ייצא", "fsg": "תצא", "mpl": "ייצאו", "fpl": "ייצאו" }
    }
  },
  {
    "id": "ntina_barosh",
    "level": 2,
    "infinitive": "לתת למישהו בראש",
    "english": "to tear into / yell at someone",
    "verb": "לתת",
    "root": "נ.ת.נ",
    "binyan": "qal",
    "object_type": "l_dative",
    "fixed_object": "בראש",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ בראש",
    "example": "אתה נותן לי בראש",
    "negated": false,
    "literal_sg": "{s} gives {o} in the head",
    "literal_pl": "{s} give {o} in the head",
    "literal_past": "{s} gave {o} in the head",
    "literal_future": "{s} will give {o} in the head",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "נותן", "fsg": "נותנת", "mpl": "נותנים", "fpl": "נותנות" },
      "past":    { "msg": "נתן", "fsg": "נתנה", "mpl": "נתנו", "fpl": "נתנו" },
      "future":  { "msg": "ייתן", "fsg": "תיתן", "mpl": "ייתנו", "fpl": "ייתנו" }
    }
  },
  {
    "id": "akhila_rosh",
    "level": 2,
    "infinitive": "לאכול למישהו את הראש",
    "english": "to nag / drive someone crazy with talk",
    "verb": "לאכול",
    "root": "א.כ.ל",
    "binyan": "qal",
    "object_type": "l_dative",
    "fixed_object": "את הראש",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את הראש",
    "example": "אתה אוכל לי את הראש",
    "negated": false,
    "literal_sg": "{s} eats {p} head",
    "literal_pl": "{s} eat {p} head",
    "literal_past": "{s} ate {p} head",
    "literal_future": "{s} will eat {p} head",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "אוכל", "fsg": "אוכלת", "mpl": "אוכלים", "fpl": "אוכלות" },
      "past":    { "msg": "אכל", "fsg": "אכלה", "mpl": "אכלו", "fpl": "אכלו" },
      "future":  { "msg": "יאכל", "fsg": "תאכל", "mpl": "יאכלו", "fpl": "יאכלו" }
    }
  },
  {
    "id": "gnivat_lev",
    "level": 2,
    "infinitive": "לגנוב למישהו את הלב",
    "english": "to steal someone's heart",
    "verb": "לגנוב",
    "root": "ג.נ.ב",
    "binyan": "qal",
    "object_type": "l_dative",
    "fixed_object": "את הלב",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את הלב",
    "example": "אתה גונב לי את הלב",
    "negated": false,
    "literal_sg": "{s} steals {p} heart",
    "literal_pl": "{s} steal {p} heart",
    "literal_past": "{s} stole {p} heart",
    "literal_future": "{s} will steal {p} heart",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "גונב", "fsg": "גונבת", "mpl": "גונבים", "fpl": "גונבות" },
      "past":    { "msg": "גנב", "fsg": "גנבה", "mpl": "גנבו", "fpl": "גנבו" },
      "future":  { "msg": "יגנוב", "fsg": "תגנוב", "mpl": "יגנבו", "fpl": "יגנבו" }
    }
  },
  {
    "id": "hotzaat_midato",
    "level": 3,
    "infinitive": "להוציא מישהו מדעתו",
    "english": "to drive someone out of their mind",
    "verb": "להוציא",
    "root": "י.צ.א",
    "binyan": "hifil",
    "object_type": "possessive_suffix",
    "suffix_noun": "דעת",
    "suffix_preposition": "מ",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩ ⟨SUFFIX_FORM⟩",
    "example": "אתה מוציא אותי מדעתי",
    "negated": false,
    "literal_sg": "{s} takes {o} out of {p} mind",
    "literal_pl": "{s} take {o} out of {p} mind",
    "literal_past": "{s} took {o} out of {p} mind",
    "literal_future": "{s} will take {o} out of {p} mind",
    "showMeaning": false,
    "suffix_forms": {
      "1sg": "מדעתי", "2msg": "מדעתך", "2fsg": "מדעתך",
      "3msg": "מדעתו", "3fsg": "מדעתה", "1pl": "מדעתנו",
      "2mpl": "מדעתכם", "2fpl": "מדעתכן", "3mpl": "מדעתם", "3fpl": "מדעתן"
    },
    "conjugations": {
      "present": { "msg": "מוציא", "fsg": "מוציאה", "mpl": "מוציאים", "fpl": "מוציאות" },
      "past":    { "msg": "הוציא", "fsg": "הוציאה", "mpl": "הוציאו", "fpl": "הוציאו" },
      "future":  { "msg": "יוציא", "fsg": "תוציא", "mpl": "יוציאו", "fpl": "יוציאו" }
    }
  },
  {
    "id": "hotzaat_miklav",
    "level": 3,
    "infinitive": "להוציא מישהו מכליו",
    "english": "to make someone totally lose it",
    "verb": "להוציא",
    "root": "י.צ.א",
    "binyan": "hifil",
    "object_type": "possessive_suffix",
    "suffix_noun": "כלים",
    "suffix_preposition": "מ",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩ ⟨SUFFIX_FORM⟩",
    "example": "אתה מוציא אותי מכליי",
    "negated": false,
    "literal_sg": "{s} takes {o} out of {p} vessels",
    "literal_pl": "{s} take {o} out of {p} vessels",
    "literal_past": "{s} took {o} out of {p} vessels",
    "literal_future": "{s} will take {o} out of {p} vessels",
    "showMeaning": true,
    "suffix_forms": {
      "1sg": "מכליי", "2msg": "מכליך", "2fsg": "מכליך",
      "3msg": "מכליו", "3fsg": "מכליה", "1pl": "מכלינו",
      "2mpl": "מכליכם", "2fpl": "מכליכן", "3mpl": "מכליהם", "3fpl": "מכליהן"
    },
    "conjugations": {
      "present": { "msg": "מוציא", "fsg": "מוציאה", "mpl": "מוציאים", "fpl": "מוציאות" },
      "past":    { "msg": "הוציא", "fsg": "הוציאה", "mpl": "הוציאו", "fpl": "הוציאו" },
      "future":  { "msg": "יוציא", "fsg": "תוציא", "mpl": "יוציאו", "fpl": "יוציאו" }
    }
  }
];

  // Normalize: expose tense aliases and english_meaning.
  return raw.map(function (item) {
    return Object.assign({}, item, {
      present_tense: item.conjugations.present,
      past_tense: item.conjugations.past || null,
      future_tense: item.conjugations.future || null,
      english_meaning: item.english,
    });
  });
})();
