(function initIvriQuestVocab(global) {
const CATEGORY_META = {
  core_advanced: {
    label: "Duolingo Advanced Core",
    description: "High-value advanced words likely adjacent to upper Duolingo content.",
    defaultSelected: true,
  },
  cooking_utensils: {
    label: "Cooking Utensils",
    description: "Kitchen tools, appliances, and food-prep hardware.",
    defaultSelected: true,
  },
  cooking_verbs: {
    label: "Cooking Verbs",
    description: "Action verbs for recipes and food prep.",
    defaultSelected: true,
  },
  health: {
    label: "Health",
    description: "Medical vocabulary for daily and clinical use.",
    defaultSelected: true,
  },
  work_business: {
    label: "Work & Business",
    description: "Workplace, management, and commerce terms.",
    defaultSelected: true,
  },
  bureaucracy: {
    label: "Bureaucracy",
    description: "Government, paperwork, legal, and administrative terms.",
    defaultSelected: true,
  },
  home_everyday_life: {
    label: "Home & Everyday Life",
    description: "Advanced household, maintenance, and daily-life vocabulary.",
    defaultSelected: true,
  },
  abstract_philosophy: {
    label: "Abstract Thinking & Philosophy",
    description: "High-level abstract and conceptual vocabulary.",
    defaultSelected: true,
  },
  emotional_nuance: {
    label: "Emotional Nuance",
    description: "Subtle emotional and interpersonal vocabulary.",
    defaultSelected: true,
  },
  conversation_glue: {
    label: "Conversation Glue",
    description: "Advanced connectors and discourse markers.",
    defaultSelected: true,
  },
  legal_civic: {
    label: "Legal & Civic Concepts",
    description: "Advanced legal, civic, and policy vocabulary.",
    defaultSelected: true,
  },
  technology_ai: {
    label: "Technology & AI",
    description: "Modern technical vocabulary for AI and software.",
    defaultSelected: true,
  },
  finance_investing: {
    label: "Finance & Investing",
    description: "Capital markets and financial fluency vocabulary.",
    defaultSelected: true,
  },
  social_cultural: {
    label: "Social & Cultural Reality",
    description: "Israeli social and cultural discourse vocabulary.",
    defaultSelected: true,
  },
  dating_relationships: {
    label: "Dating & Relationships",
    description: "Modern relationship and dating vocabulary.",
    defaultSelected: true,
  },
  meta_language: {
    label: "Meta-Language",
    description: "Language-learning and linguistic vocabulary.",
    defaultSelected: true,
  },
  scientific_analytical: {
    label: "Scientific & Analytical",
    description: "Scientific reasoning and analytical discourse vocabulary.",
    defaultSelected: true,
  },
  abstract_concepts_expanded: {
    label: "Abstract Concepts (Expanded)",
    description: "Formal logic, argumentation, and abstract framing language.",
    defaultSelected: true,
  },
  emotional_psychological_expanded: {
    label: "Emotional & Psychological (Expanded)",
    description: "Advanced emotional regulation, trauma, and relational dynamics vocabulary.",
    defaultSelected: true,
  },
  relationships_dating_expanded: {
    label: "Relationships & Dating (Expanded)",
    description: "Advanced vocabulary for romance, commitment, conflict, and family ties.",
    defaultSelected: true,
  },
  politics_society_expanded: {
    label: "Politics & Society (Expanded)",
    description: "Civic discourse, elections, activism, governance, and identity politics.",
    defaultSelected: true,
  },
  law_legal_systems_expanded: {
    label: "Law & Legal Systems (Expanded)",
    description: "Procedural, contractual, criminal, and regulatory legal language.",
    defaultSelected: true,
  },
  technology_ai_expanded: {
    label: "Technology & AI (Expanded)",
    description: "Machine learning, cybersecurity, privacy, software, and startup vocabulary.",
    defaultSelected: true,
  },
  business_finance_expanded: {
    label: "Business & Finance (Expanded)",
    description: "Corporate, accounting, markets, insurance, and tax vocabulary.",
    defaultSelected: true,
  },
  science_research_expanded: {
    label: "Science & Research (Expanded)",
    description: "Research design, statistics, evidence, and scientific-domain language.",
    defaultSelected: true,
  },
  philosophy_intellectual_expanded: {
    label: "Philosophy & Intellectual Life (Expanded)",
    description: "Ethics, epistemology, logic, and existential discourse vocabulary.",
    defaultSelected: true,
  },
  culture_identity_expanded: {
    label: "Culture & Identity (Expanded)",
    description: "Israeli cultural, religious, social identity, and public-life vocabulary.",
    defaultSelected: true,
  },
  communication_mastery_expanded: {
    label: "Communication Mastery (Expanded)",
    description: "Public speaking, negotiation, writing, rhetoric, and subtext vocabulary.",
    defaultSelected: true,
  },
  everyday_survival_expanded: {
    label: "Everyday Advanced Survival (Expanded)",
    description: "Apartment, bureaucracy, customer service, repairs, and travel-complication vocabulary.",
    defaultSelected: true,
  },
  media_digital_life_expanded: {
    label: "Media & Digital Life (Expanded)",
    description: "Online discourse, social media, streaming, gaming, and meme vocabulary.",
    defaultSelected: true,
  },
  health_body_expanded: {
    label: "Health & Body (Expanded)",
    description: "Advanced nutrition, fitness, medicine, insurance, and treatment vocabulary.",
    defaultSelected: true,
  },
  advanced_grammar_meta_expanded: {
    label: "Advanced Grammar & Meta-Language (Expanded)",
    description: "Linguistics, morphology, register, and historical language vocabulary.",
    defaultSelected: true,
  },
  high_level_discourse_expanded: {
    label: "High-Level Discourse Tier (Expanded)",
    description: "Think tank, policy, strategic planning, governance, and forecasting vocabulary.",
    defaultSelected: true,
  },
};

const EXPANSION_TRACKS = {
  "Abstract & Discourse": [
    "Abstract Concepts",
    "Logical Connectors (Formal)",
    "Logical Connectors (Colloquial)",
    "Argumentation & Debate",
    "Rhetorical Language",
    "Persuasion Vocabulary",
    "Academic Writing",
    "Opinion & Stance",
    "Certainty & Uncertainty",
    "Probability & Risk",
    "Contrast & Concession",
    "Emphasis & Qualification",
  ],
  "Emotional & Psychological": [
    "Emotional Nuance",
    "Interpersonal Conflict",
    "Attachment & Relationships",
    "Trauma & Recovery",
    "Mental Health (Advanced)",
    "Self-Reflection Vocabulary",
    "Boundaries & Autonomy",
    "Motivation & Discipline",
    "Personality Traits (Positive)",
    "Personality Traits (Negative)",
    "Social Dynamics",
    "Power & Control",
  ],
  "Relationships & Dating": [
    "Dating & Romance",
    "Commitment & Exclusivity",
    "Breakups & Closure",
    "Long-Distance Relationships",
    "Red Flags & Green Flags",
    "Flirting & Attraction",
    "Marriage & Family Life",
    "Parenting Vocabulary",
    "In-Laws & Extended Family",
  ],
  "Politics & Society": [
    "Israeli Society",
    "Religion & Secularism",
    "Democracy & Governance",
    "Public Policy",
    "Elections & Campaigns",
    "Protest & Activism",
    "Media & Journalism",
    "Geopolitics",
    "National Security",
    "Civil Rights",
    "Polarization & Identity",
  ],
  "Law & Legal Systems": [
    "Constitutional Law",
    "Criminal Law",
    "Civil Litigation",
    "Contracts & Liability",
    "Courtroom Vocabulary",
    "Evidence & Procedure",
    "Immigration Law",
    "Property Law",
    "Corporate Law",
    "Regulatory Compliance",
  ],
  "Technology & AI": [
    "Artificial Intelligence",
    "Machine Learning",
    "Neural Networks",
    "Data Science",
    "Cybersecurity",
    "Privacy & Surveillance",
    "Open Source & Licensing",
    "Robotics",
    "Automation & Industry",
    "Software Engineering",
    "Product Development",
    "Startups & Venture Capital",
  ],
  "Business & Finance": [
    "Investing & Capital Markets",
    "Personal Finance",
    "Banking & Credit",
    "Accounting",
    "Corporate Governance",
    "Mergers & Acquisitions",
    "Entrepreneurship",
    "Macroeconomics",
    "Microeconomics",
    "Real Estate",
    "Insurance",
    "Taxes (Advanced)",
  ],
  "Science & Research": [
    "Scientific Method",
    "Research Design",
    "Statistics",
    "Data Analysis",
    "Medical Science",
    "Biology",
    "Physics",
    "Chemistry",
    "Environmental Science",
    "Climate Change",
  ],
  "Philosophy & Intellectual Life": [
    "Ethics & Morality",
    "Epistemology",
    "Identity & Consciousness",
    "Free Will & Determinism",
    "Existentialism",
    "Religious Philosophy",
    "Political Philosophy",
    "Metaphysics",
    "Logic",
  ],
  "Culture & Identity": [
    "Israeli Cultural References",
    "Jewish Religious Vocabulary",
    "Holidays & Rituals",
    "Secular Israeli Slang",
    "Military Service",
    "Pop Culture",
    "Music & Entertainment",
    "LGBTQ+ Vocabulary",
    "Social Class & Status",
  ],
  "Communication Mastery": [
    "Public Speaking",
    "Negotiation",
    "Conflict Resolution",
    "Diplomacy",
    "Email & Professional Writing",
    "Informal Texting Language",
    "Idioms & Expressions",
    "Slang (Contemporary)",
    "Sarcasm & Humor",
    "Irony & Subtext",
  ],
  "Everyday Advanced Survival": [
    "Apartment Hunting",
    "Utilities & Bills",
    "Contracts & Leases",
    "Car Ownership",
    "Insurance Claims",
    "Complaints & Customer Service",
    "Bureaucratic Navigation",
    "Repairs & Emergencies",
    "Travel Complications",
  ],
  "Media & Digital Life": [
    "Social Media",
    "Online Discourse",
    "Influencers & Content Creation",
    "Streaming & Entertainment",
    "Gaming Vocabulary",
    "Internet Slang",
    "Memes & Cultural References",
  ],
  "Health & Body (Expanded)": [
    "Nutrition Science",
    "Fitness & Training",
    "Sports Medicine",
    "Chronic Conditions",
    "Medical Bureaucracy",
    "Insurance Disputes",
    "Preventative Care",
  ],
  "Advanced Grammar & Meta-Language": [
    "Linguistics Terminology",
    "Roots & Word Formation",
    "Binyanim (Verb Patterns)",
    "Nominal Patterns",
    "Register Differences",
    "Formal vs Informal Speech",
    "Biblical vs Modern Hebrew",
    "Aramaic Influences",
  ],
  "High-Level Discourse Tier": [
    "Think Tank Vocabulary",
    "Policy White Papers",
    "Risk Assessment",
    "Strategic Planning",
    "Institutional Governance",
    "International Relations",
    "Security Doctrine",
    "Technological Forecasting",
  ],
};

const RAW = {
  core_advanced: [
    ["priority", "עדיפות", "עֲדִיפוּת"],
    ["responsibility", "אחריות", "אַחֲרָיוּת"],
    ["opportunity", "הזדמנות", "הִזְדַּמְּנוּת"],
    ["requirement", "דרישה", "דְּרִישָׁה"],
    ["evidence", "ראיה", "רְאָיָה"],
    ["outcome", "תוצאה", "תּוֹצָאָה"],
    ["approach", "גישה", "גִּישָׁה"],
    ["assumption", "הנחה", "הַנָּחָה"],
    ["concern", "חשש", "חֲשָׁשׁ"],
    ["awareness", "מודעות", "מוּדָעוּת"],
    ["resource", "משאב", "מַשְׁאָב"],
    ["solution", "פתרון", "פִּתְרוֹן"],
    ["progress", "התקדמות", "הִתְקַדְּמוּת"],
    ["relationship", "מערכת יחסים", "מַעֲרֶכֶת יְחָסִים"],
    ["communication", "תקשורת", "תִּקְשֹׁרֶת"],
    ["argument", "טיעון", "טִעוּן"],
    ["discussion", "דיון", "דִּיּוּן"],
    ["decision", "החלטה", "הַחְלָטָה"],
    ["mistake", "טעות", "טָעוּת"],
    ["advantage", "יתרון", "יִתְרוֹן"],
    ["disadvantage", "חיסרון", "חִסָּרוֹן"],
    ["compromise", "פשרה", "פְּשָׁרָה"],
    ["expectation", "ציפייה", "צִפִּיָּה"],
    ["confidence", "ביטחון", "בִּטָּחוֹן"],
    ["patience", "סבלנות", "סַבְלָנוּת"],
    ["flexibility", "גמישות", "גְּמִישׁוּת"],
    ["reliability", "אמינות", "אֲמִינוּת"],
    ["availability", "זמינות", "זְמִינוּת"],
    ["schedule", "לוח זמנים", "לוּחַ זְמַנִּים"],
    ["improvement", "שיפור", "שִׁפּוּר"],
    ["failure", "כישלון", "כִּשָּׁלוֹן"],
    ["success", "הצלחה", "הַצְלָחָה"],
    ["attempt", "ניסיון", "נִסָּיוֹן"],
    ["support", "תמיכה", "תְּמִיכָה"],
    ["recommendation", "המלצה", "הַמְלָצָה"],
    ["possibility", "אפשרות", "אֶפְשָׁרוּת"],
    ["probability", "הסתברות", "הִסְתַּבְּרוּת"],
    ["demand", "ביקוש", "בִּקּוּשׁ"],
    ["supply", "היצע", "הֶיצֵּעַ"],
    ["capacity", "קיבולת", "קִיבּוֹלֶת"],
    ["quality", "איכות", "אֵיכוּת"],
    ["quantity", "כמות", "כַּמּוּת"],
    ["average", "ממוצע", "מְמוּצָע"],
    ["percentage", "אחוז", "אָחוּז"],
    ["comparison", "השוואה", "הַשְׁוָאָה"],
    ["difference", "הבדל", "הֶבְדֵּל"],
    ["similarity", "דמיון", "דִּמְיוֹן"],
    ["trend", "מגמה", "מְגַמָּה"],
    ["habit", "הרגל", "הֶרְגֵּל"],
    ["routine", "שגרה", "שִׁגְרָה"],
    ["custom", "מנהג", "מִנְהָג"],
    ["tradition", "מסורת", "מַסּוֹרֶת"],
    ["culture", "תרבות", "תַּרְבּוּת"],
    ["value", "ערך", "עֵרֶךְ"],
    ["principle", "עיקרון", "עִקָּרוֹן"],
    ["respect", "כבוד", "כָּבוֹד"],
    ["privacy", "פרטיות", "פְּרָטִיּוּת"],
    ["security", "אבטחה", "אַבְטָחָה"],
    ["safety", "בטיחות", "בְּטִיחוּת"],
    ["warning", "אזהרה", "אַזְהָרָה"],
    ["permission", "רשות", "רְשׁוּת"],
    ["obligation / mandatory", "חובה", "חוֹבָה"],
    ["forbidden", "אסור", "אָסוּר"],
    ["allowed", "מותר", "מוּתָר"],
    ["temporary", "זמני", "זְמַנִּי"],
    ["permanent", "קבוע", "קָבוּעַ"],
    ["urgent", "דחוף", "דָּחוּף"],
    ["optional", "אופציונלי", "אוֹפְּצִיוֹנָלִי"],
    ["recent", "עדכני", "עַדְכָּנִי"],
    ["previous", "קודם", "קוֹדֵם"],
    ["next", "הבא", "הַבָּא"],
    ["entire", "שלם", "שָׁלֵם"],
    ["partial", "חלקי", "חֶלְקִי"],
    ["scene (of)", "זירת", "זִירַת"],
    ["disaster", "אסון", "אָסוֹן"],
    ["operation", "מבצע", "מִבְצָע"],
    ["treasure chest", "תיבת אוצר", "תֵּיבַת אוֹצָר"],
    ["locating", "איתור", "אִיתּוּר"],
    ["suddenly", "פתאום", "פִּתְאוֹם"],
    ["burning", "בוער", "בּוֹעֵר"],
    ["crushing", "כותש", "כּוֹתֵשׁ"],
    ["killing (participle)", "הורג", "הוֹרֵג"],
    ["obstacle", "מכשול", "מִכְשׁוֹל"],
    ["barrier", "חסם", "חֶסֶם"],
    ["front", "חזית", "חֲזִית"],
    ["roar of", "שאגת", "שַׁאֲגַת"],
    ["was eliminated", "חוסל", "חֻסַּל"],
    ["council", "מועצה", "מוֹעָצָה"],
    ["infiltration", "חדירה", "חֲדִירָה"],
    ["hostile", "עוין", "עוֹיֵן"],
    ["campaign", "מערכה", "מַעֲרָכָה"],
    ["regime", "משטר", "מִשְׁטָר"],
    ["guidelines", "הנחיות", "הַנְחָיוֹת"],
    ["interception", "יירוט", "יִירוּט"],
    ["to intercept", "ליירט", "לְיַירֵט"],
    ["facility", "מתקן", "מִתְקָן"],
    ["deputy", "סגן", "סְגָן"],
    ["squalor", "עליבות", "עֲלִיבוּת"],
    ["accurate", "מדויק", "מְדוּיָּק"],
    ["approximate", "משוער", "מְשֹׁעָר"],
    ["meanwhile", "בינתיים", "בֵּינְתַיִם"],
    ["instead", "במקום זאת", "בִּמְקוֹם זֹאת"],
    ["although", "אף על פי", "אַף עַל פִּי"],
    ["however", "עם זאת", "עִם זֹאת"],
    ["therefore", "לכן", "לָכֵן"],
    ["furthermore", "בנוסף", "בְּנוֹסָף"],
    ["nevertheless", "למרות זאת", "לַמְרוֹת זֹאת"],
    ["in general", "באופן כללי", "בְּאוֹפֶן כְּלָלִי"],
    ["in particular", "בפרט", "בִּפְרָט"],
    ["for example", "למשל", "לְמָשָׁל"],
    ["on the other hand", "מצד שני", "מִצַּד שֵׁנִי"],
    ["in conclusion", "לסיכום", "לְסִכּוּם"],
    ["at least", "לפחות", "לְפָחוֹת"],
    ["at most", "לכל היותר", "לְכָל הַיּוֹתֵר"],
    ["as soon as possible", "בהקדם האפשרי", "בְּהֶקְדֵּם הָאֶפְשָׁרִי"],
  ],
  cooking_utensils: [
    ["knife", "סכין", "סַכִּין"],
    ["chef's knife", "סכין שף", "סַכִּין שֶׁף"],
    ["paring knife", "סכין לקילוף", "סַכִּין לְקִלּוּף"],
    ["serrated knife", "סכין משוננת", "סַכִּין מְשֻׁנֶּנֶת"],
    ["cleaver", "קופיץ", "קוֹפִּיץ"],
    ["cutting board", "קרש חיתוך", "קֶרֶשׁ חִיתּוּךְ"],
    ["mixing bowl", "קערת ערבוב", "קְעָרַת עִרְבּוּב"],
    ["bowl", "קערה", "קְעָרָה"],
    ["whisk", "מטרפה", "מַטְרֵפָה"],
    ["spatula", "מרית", "מָרִית"],
    ["turner", "כף להפיכה", "כַּף לַהֲפִיכָה"],
    ["wooden spoon", "כף עץ", "כַּף עֵץ"],
    ["ladle", "מצקת", "מַצֶּקֶת"],
    ["slotted spoon", "כף מחוררת", "כַּף מְחוֹרֶרֶת"],
    ["tongs", "מלקחיים", "מֶלְקָחַיִם"],
    ["peeler", "קולפן", "קוֹלְפָן"],
    ["grater", "פומפייה", "פּוּמְפִּיָּה"],
    ["zester", "מגרדת הדרים", "מְגָרֶדֶת הֲדָרִים"],
    ["sieve", "מסננת", "מְסַנֶּנֶת"],
    ["colander", "מסננת פסטה", "מְסַנֶּנֶת פַּסְטָה"],
    ["funnel", "משפך", "מַשְׁפֵּךְ"],
    ["measuring cup", "כוס מדידה", "כּוֹס מְדִידָה"],
    ["measuring spoon", "כפית מדידה", "כְּפִית מְדִידָה"],
    ["rolling pin", "מערוך", "מַעֲרוֹךְ"],
    ["mortar", "מכתש", "מַכְתֵּשׁ"],
    ["pestle", "עלי", "עָלִי"],
    ["garlic press", "מועך שום", "מוֹעֵךְ שׁוּם"],
    ["can opener", "פותחן קופסאות", "פּוֹתְחָן קֻפְסָאוֹת"],
    ["bottle opener", "פותחן בקבוקים", "פּוֹתְחָן בַּקְבּוּקִים"],
    ["corkscrew", "חולץ פקקים", "חוֹלֵץ פְּקָקִים"],
    ["kitchen scale", "משקל מטבח", "מִשְׁקַל מִטְבָּח"],
    ["timer", "טיימר", "טַיְימֶר"],
    ["thermometer", "מדחום", "מַדְחוֹם"],
    ["oven mitt", "כפפת תנור", "כְּפֶפֶת תַּנּוּר"],
    ["apron", "סינר", "סִינָר"],
    ["baking tray", "תבנית אפייה", "תַּבְנִית אֲפִיָּה"],
    ["roasting pan", "תבנית צלייה", "תַּבְנִית צְלִיָּה"],
    ["skillet", "מחבת", "מַחֲבַת"],
    ["frying pan", "מחבת טיגון", "מַחֲבַת טִיגּוּן"],
    ["saucepan", "קלחת", "קַלַּחַת"],
    ["stockpot", "סיר מרק", "סִיר מָרָק"],
    ["pressure cooker", "סיר לחץ", "סִיר לַחַץ"],
    ["steamer", "סיר אידוי", "סִיר אִידּוּי"],
    ["wok", "ווק", "ווֹק"],
    ["grill pan", "מחבת גריל", "מַחֲבַת גְּרִיל"],
    ["baking dish", "כלי אפייה", "כְּלִי אֲפִיָּה"],
    ["casserole dish", "תבנית קדירה", "תַּבְנִית קְדֵרָה"],
    ["loaf pan", "תבנית אינגליש קייק", "תַּבְנִית אִינְגְּלִישׁ קֵייק"],
    ["muffin tin", "תבנית מאפינס", "תַּבְנִית מָאפִינְס"],
    ["pie dish", "תבנית פאי", "תַּבְנִית פַּאי"],
    ["parchment paper", "נייר אפייה", "נְיָר אֲפִיָּה"],
    ["aluminum foil", "נייר אלומיניום", "נְיָר אֲלוּמִינְיוּם"],
    ["plastic wrap", "ניילון נצמד", "נַיְלוֹן נִצְמָד"],
    ["storage container", "קופסת אחסון", "קֻפְסַת אִחְסוּן"],
    ["blender", "בלנדר", "בְּלֶנְדֶר"],
    ["food processor", "מעבד מזון", "מְעַבֵּד מָזוֹן"],
    ["mixer", "מיקסר", "מִיקְסֶר"],
    ["hand mixer", "מיקסר ידני", "מִיקְסֶר יָדָנִי"],
    ["immersion blender", "בלנדר מוט", "בְּלֶנְדֶר מוֹט"],
    ["spice grinder", "מטחנת תבלינים", "מַטְחֶנֶת תַּבְלִינִים"],
    ["kettle", "קומקום", "קוּמְקוּם"],
    ["toaster", "טוסטר", "טוֹסְטֶר"],
    ["oven", "תנור", "תַּנּוּר"],
    ["microwave", "מיקרוגל", "מִיקְרוֹגַל"],
    ["refrigerator", "מקרר", "מְקָרֵר"],
    ["freezer", "מקפיא", "מַקְפִּיא"],
    ["sink", "כיור", "כִּיּוֹר"],
    ["faucet", "ברז", "בֶּרֶז"],
    ["dish rack", "מייבש כלים", "מְיַבֵּשׁ כֵּלִים"],
    ["dishwasher", "מדיח כלים", "מַדִּיחַ כֵּלִים"],
    ["pastry brush", "מברשת אפייה", "מִבְרֶשֶׁת אֲפִיָּה"],
    ["pastry bag", "שקית זילוף", "שַׂקִּית זִלּוּף"],
    ["cookie cutter", "קורצן", "קוֹרְצָן"],
    ["skimmer", "כף קצף", "כַּף קֶצֶף"],
    ["mandoline slicer", "מנדולינה", "מַנְדּוֹלִינָה"],
  ],
  cooking_verbs: [
    ["to chop", "לקצוץ", "לְקַצֵּץ"],
    ["to dice", "לחתוך לקוביות", "לַחְתּוֹךְ לְקוּבִיּוֹת"],
    ["to slice", "לפרוס", "לִפְרוֹס"],
    ["to mince", "לקצוץ דק", "לְקַצֵּץ דַּק"],
    ["to peel", "לקלף", "לְקַלֵּף"],
    ["to grate / scrape", "לגרד", "לְגָרֵד"],
    ["to whisk", "לטרוף", "לִטְרוֹף"],
    ["to stir / mix", "לערבב", "לְעַרְבֵּב"],
    ["to fold", "לקפל", "לְקַפֵּל"],
    ["to beat / whip", "להקציף", "לְהַקְצִיף"],
    ["to knead", "ללוש", "לָלוּשׁ"],
    ["to roll out", "לרדד", "לְרַדֵּד"],
    ["to sift", "לנפות", "לְנַפּוֹת"],
    ["to measure", "למדוד", "לִמְדוֹד"],
    ["to pour", "למזוג", "לִמְזוֹג"],
    ["to drizzle", "לזלף", "לְזַלֵּף"],
    ["to season", "לתבל", "לְתַבֵּל"],
    ["to marinate", "להשרות במרינדה", "לְהַשְׁרוֹת בְּמָרִינָדָה"],
    ["to soak", "להשרות", "לְהַשְׁרוֹת"],
    ["to boil", "להרתיח", "לְהַרְתִּיחַ"],
    ["to simmer", "לבשל על אש קטנה", "לְבַשֵּׁל עַל אֵשׁ קְטַנָּה"],
    ["to poach", "לחלוט", "לַחְלוֹט"],
    ["to steam", "לאדות", "לְאַדּוֹת"],
    ["to fry", "לטגן", "לְטַגֵּן"],
    ["to deep-fry", "לטגן בשמן עמוק", "לְטַגֵּן בְּשֶׁמֶן עָמוֹק"],
    ["to saute", "להקפיץ", "לְהַקְפִּיץ"],
    ["to sear", "לצרוב", "לִצְרוֹב"],
    ["to grill", "לצלות על גריל", "לִצְלוֹת עַל גְּרִיל"],
    ["to roast", "לצלות", "לִצְלוֹת"],
    ["to bake", "לאפות", "לֶאֱפוֹת"],
    ["to broil", "לצלות בתנור", "לִצְלוֹת בַּתַּנּוּר"],
    ["to toast", "לקלות", "לִקְלוֹת"],
    ["to blanch", "לחלוט", "לַחְלוֹט"],
    ["to caramelize", "לקרמל", "לְקַרְמֵל"],
    ["to reduce", "לצמצם", "לְצַמְצֵם"],
    ["to thicken", "להסמיך", "לְהַסְמִיךְ"],
    ["to dilute", "לדלל", "לְדַלֵּל"],
    ["to strain", "לסנן", "לְסַנֵּן"],
    ["to drain", "לנקז", "לְנַקֵּז"],
    ["to rinse", "לשטוף", "לִשְׁטוֹף"],
    ["to preheat", "לחמם מראש", "לְחַמֵּם מֵרֹאשׁ"],
    ["to defrost", "להפשיר", "לְהַפְשִׁיר"],
    ["to freeze", "להקפיא", "לְהַקְפִּיא"],
    ["to refrigerate", "לקרר", "לְקָרֵר"],
    ["to chill", "לצנן", "לְצַנֵּן"],
    ["to garnish", "לקשט", "לְקַשֵּׁט"],
    ["to serve", "להגיש", "לְהַגִּישׁ"],
    ["to plate", "לסדר בצלחת", "לְסַדֵּר בַּצַּלַּחַת"],
    ["to taste", "לטעום", "לִטְעוֹם"],
    ["to adjust seasoning", "לתקן תיבול", "לְתַקֵּן תִּיבּוּל"],
    ["to overcook", "לבשל יתר על המידה", "לְבַשֵּׁל יֶתֶר עַל הַמִּדָּה"],
    ["to undercook", "לבשל פחות מדי", "לְבַשֵּׁל פָּחוֹת מִדַּי"],
    ["to burn", "לשרוף", "לִשְׂרוֹף"],
    ["to ignite", "להצית", "לְהַצִּית"],
    ["to smoke", "לעשן", "לְעַשֵּׁן"],
    ["to ferment", "להתסיס", "לְהַתְסִיס"],
    ["to pickle", "לכבוש", "לִכְבּוֹשׁ"],
    ["to blend", "לטחון", "לִטְחוֹן"],
    ["to puree", "לרסק למחית", "לְרַסֵּק לִמְחִית"],
    ["to smash", "לרסק", "לְרַסֵּק"],
    ["to crush", "למחוץ", "לִמְחוֹץ"],
    ["to mash", "למעוך", "לִמְעוֹךְ"],
    ["to skewer", "לשפד", "לְשַׁפֵּד"],
    ["to core", "להוציא ליבה", "לְהוֹצִיא לִבָּה"],
    ["to pit", "לגלען", "לְגַלְעֵן"],
    ["to zest", "לגרד קליפה", "לְגָרֵד קְלִפָּה"],
    ["to grease", "לשמן", "לְשַׁמֵּן"],
    ["to line a pan", "לרפד תבנית", "לְרַפֵּד תַּבְנִית"],
    ["to flip", "להפוך", "לַהֲפוֹךְ"],
    ["to toss", "להקפיץ", "לְהַקְפִּיץ"],
    ["to coat", "לצפות", "לְצַפּוֹת"],
    ["to breadcrumb", "לצפות בפירורים", "לְצַפּוֹת בְּפֵרוּרִים"],
    ["to braise", "לבשל בנוזל מועט", "לְבַשֵּׁל בְּנוֹזֵל מוּעָט"],
    ["to stew", "לבשל קדירה", "לְבַשֵּׁל קְדֵרָה"],
  ],
  health: [
    ["nurse", "אחות", "אָחוֹת"],
    ["hospital", "בית חולים", "בֵּית חוֹלִים"],
    ["clinic", "מרפאה", "מִרְפָּאָה"],
    ["emergency room", "חדר מיון", "חֶדֶר מִיּוּן"],
    ["appointment", "תור", "תּוֹר"],
    ["prescription", "מרשם", "מִרְשָׁם"],
    ["medicine", "תרופה", "תְּרוּפָה"],
    ["pill", "כדור", "כַּדּוּר"],
    ["dose", "מינון", "מִינוּן"],
    ["symptom", "תסמין", "תַּסְמִין"],
    ["diagnosis", "אבחנה", "אִבְחָנָה"],
    ["treatment", "טיפול", "טִפּוּל"],
    ["therapy", "תרפיה", "תֶּרַפְּיָה"],
    ["surgery", "ניתוח", "נִיתּוּחַ"],
    ["anesthesia", "הרדמה", "הַרְדָּמָה"],
    ["vaccination", "חיסון", "חִסּוּן"],
    ["side effect", "תופעת לוואי", "תוֹפַעַת לְוַאי"],
    ["allergy", "אלרגיה", "אַלֶּרְגְּיָה"],
    ["infection", "זיהום", "זִיהוּם"],
    ["inflammation", "דלקת", "דַלֶּקֶת"],
    ["fever", "חום", "חוֹם"],
    ["cough", "שיעול", "שִׁעוּל"],
    ["sore throat", "כאב גרון", "כְּאֵב גָּרוֹן"],
    ["headache", "כאב ראש", "כְּאֵב רֹאשׁ"],
    ["stomachache", "כאב בטן", "כְּאֵב בֶּטֶן"],
    ["nausea", "בחילה", "בְּחִילָה"],
    ["dizziness", "סחרחורת", "סַחְרְחוֹרֶת"],
    ["blood pressure", "לחץ דם", "לַחַץ דָּם"],
    ["pulse", "דופק", "דֹּפֶק"],
    ["heart rate", "קצב לב", "קֶצֶב לֵב"],
    ["diabetes", "סוכרת", "סֻכֶּרֶת"],
    ["asthma", "אסתמה", "אַסְתְּמָה"],
    ["hypertension", "יתר לחץ דם", "יֶתֶר לַחַץ דָּם"],
    ["cholesterol", "כולסטרול", "כוֹלֶסְטֵרוֹל"],
    ["obesity", "השמנה", "הַשְׁמָנָה"],
    ["nutrition", "תזונה", "תְּזוּנָה"],
    ["diet", "תפריט", "תַּפְרִיט"],
    ["exercise", "פעילות גופנית", "פְּעִילוּת גּוּפָנִית"],
    ["workout", "אימון", "אִמּוּן"],
    ["physiotherapy", "פיזיותרפיה", "פִיזְיוֹתֶּרַפְּיָה"],
    ["mental health", "בריאות נפש", "בְּרִיאוּת נֶפֶשׁ"],
    ["anxiety", "חרדה", "חֲרָדָה"],
    ["depression", "דיכאון", "דִּכָּאוֹן"],
    ["stress", "לחץ נפשי", "לַחַץ נַפְשִׁי"],
    ["insomnia", "נדודי שינה", "נְדוּדֵי שֵׁנָה"],
    ["sleep apnea", "דום נשימה בשינה", "דּוֹם נְשִׁימָה בַּשֵּׁנָה"],
    ["health insurance", "ביטוח בריאות", "בִּטּוּחַ בְּרִיאוּת"],
    ["deductible", "השתתפות עצמית", "הִשְׁתַּתְּפוּת עַצְמִית"],
    ["referral", "הפניה", "הַפְנָיָה"],
    ["specialist", "מומחה", "מוּמְחֶה"],
    ["rehabilitation", "שיקום", "שִׁקּוּם"],
    ["chronic", "כרוני", "כְּרוֹנִי"],
    ["acute", "חריף", "חָרִיף"],
    ["prevention", "מניעה", "מְנִיעָה"],
    ["screening", "בדיקת סקר", "בְּדִיקַת סֶקֶר"],
    ["blood test", "בדיקת דם", "בְּדִיקַת דָּם"],
    ["x-ray", "צילום רנטגן", "צִלוּם רֶנְטְגֶן"],
    ["ultrasound", "אולטרסאונד", "אוּלְטְרָסָאוּנְד"],
    ["emergency", "חירום", "חֵירוּם"],
    ["first aid", "עזרה ראשונה", "עֶזְרָה רִאשׁוֹנָה"],
    ["paramedic", "חובש", "חוֹבֵשׁ"],
    ["ambulance", "אמבולנס", "אַמְבּוּלַנְס"],
    ["pharmacy", "בית מרקחת", "בֵּית מִרְקַחַת"],
    ["bandage", "תחבושת", "תַּחְבּוֹשֶׁת"],
    ["stitches", "תפרים", "תְּפָרִים"],
    ["fracture", "שבר", "שֶׁבֶר"],
    ["sprain", "נקע", "נֶקַע"],
    ["rash", "פריחה", "פְּרִיחָה"],
    ["dehydration", "התייבשות", "הִתְיַבְּשׁוּת"],
    ["doctor", "רופא", "רוֹפֵא"],
    ["chiropractor", "כירופרקטור", "כִּירוֹפְּרַקְטוֹר"],
  ],
  work_business: [
    ["agenda", "סדר יום", "סֵדֶר יוֹם"],
    ["deadline", "מועד אחרון", "מוֹעֵד אַחֲרוֹן"],
    ["task", "משימה", "מְשִׂימָה"],
    ["deliverable", "תוצר", "תּוֹצָר"],
    ["proposal", "הצעה", "הַצָּעָה"],
    ["contract", "חוזה", "חוֹזֶה"],
    ["invoice", "חשבונית", "חֶשְׁבּוֹנִית"],
    ["receipt", "קבלה", "קַבָּלָה"],
    ["budget", "תקציב", "תַּקְצִיב"],
    ["revenue", "הכנסות", "הַכְנָסוֹת"],
    ["profit", "רווח", "רֶוַח"],
    ["loss", "הפסד", "הֶפְסֵד"],
    ["expense", "הוצאה", "הוֹצָאָה"],
    ["cash flow", "תזרים מזומנים", "תַּזְרִים מְזוּמָנִים"],
    ["payroll", "שכר", "שָׂכָר"],
    ["salary", "משכורת", "מַשְׂכּוֹרֶת"],
    ["bonus", "בונוס", "בּוֹנוּס"],
    ["raise", "העלאה בשכר", "הַעֲלָאָה בְּשָׂכָר"],
    ["promotion", "קידום", "קִדּוּם"],
    ["performance review", "הערכת ביצועים", "הַעֲרָכַת בִּיצּוּעִים"],
    ["stakeholder", "בעל עניין", "בַּעַל עִנְיָן"],
    ["client", "לקוח", "לָקוֹחַ"],
    ["supplier", "ספק", "סַפָּק"],
    ["negotiation", "משא ומתן", "מַשָּׂא וּמַתָּן"],
    ["strategy", "אסטרטגיה", "אֶסְטְרָטֶגְיָה"],
    ["execution", "ביצוע", "בִּיצּוּעַ"],
    ["roadmap", "מפת דרכים", "מַפַּת דְּרָכִים"],
    ["milestone", "אבן דרך", "אֶבֶן דֶּרֶךְ"],
    ["risk", "סיכון", "סִיכּוּן"],
    ["compliance", "ציות", "צִיּוּת"],
    ["policy", "מדיניות", "מְדִינִיּוּת"],
    ["procedure", "נוהל", "נֹהַל"],
    ["onboarding", "קליטה", "קְלִיטָה"],
    ["training", "הדרכה", "הַדְרָכָה"],
    ["recruitment", "גיוס", "גִּיּוּס"],
    ["interview", "ראיון", "רֵאָיוֹן"],
    ["resume", "קורות חיים", "קוֹרוֹת חַיִּים"],
    ["leadership", "מנהיגות", "מַנְהִיגוּת"],
    ["management", "ניהול", "נִיהוּל"],
    ["accountability", "אחריותיות", "אַחֲרָיוּתִיּוּת"],
    ["productivity", "תפוקה", "תְּפוּקָה"],
    ["efficiency", "יעילות", "יְעִילוּת"],
    ["quality assurance", "אבטחת איכות", "אַבְטָחַת אֵיכוּת"],
    ["customer support", "תמיכת לקוחות", "תְּמִיכַת לָקוֹחוֹת"],
    ["feedback", "משוב", "מָשׁוֹב"],
    ["KPI", "מדד ביצוע מרכזי", "מַדַּד בִּיצּוּעַ מֶרְכָּזִי"],
    ["growth", "צמיחה", "צְמִיחָה"],
    ["marketing", "שיווק", "שִׁוּוּק"],
    ["campaign", "קמפיין", "קַמְפֵּיְין"],
    ["sales", "מכירות", "מְכִירוֹת"],
    ["pipeline", "צינור מכירות", "צִנּוֹר מְכִירוֹת"],
    ["forecast", "תחזית", "תַּחֲזִית"],
    ["audit", "ביקורת", "בִּקּוֹרֶת"],
    ["merger", "מיזוג", "מִיזּוּג"],
    ["acquisition", "רכישה", "רְכִישָׁה"],
    ["startup", "סטארטאפ", "סְטַארְטְאַפּ"],
    ["enterprise", "תאגיד", "תַּאֲגִיד"],
    ["remote work", "עבודה מרחוק", "עֲבוֹדָה מֵרָחוֹק"],
    ["hybrid work", "עבודה היברידית", "עֲבוֹדָה הִיבְּרִידִית"],
    ["work-life balance", "איזון עבודה-חיים", "אִיזּוּן עֲבוֹדָה-חַיִּים"],
    ["overtime", "שעות נוספות", "שָׁעוֹת נוֹסָפוֹת"],
    ["resignation", "התפטרות", "הִתְפַּטְּרוּת"],
    ["to fire (dismiss)", "לפטר", "לְפַטֵּר"],
    ["termination", "פיטורים", "פִּטּוּרִים"],
    ["severance pay", "פיצויי פיטורים", "פִּצּוּיֵי פִּטּוּרִים"],
    ["union", "איגוד עובדים", "אִיגּוּד עוֹבְדִים"],
    ["entrepreneurship", "יזמות", "יַזְמוּת"],
    ["equity", "הון עצמי", "הוֹן עַצְמִי"],
    ["valuation", "שווי", "שְׁוִי"],
    ["board of directors", "דירקטוריון", "דִּירֶקְטוֹרְיוֹן"],
    ["shareholder", "בעל מניות", "בַּעַל מְנָיוֹת"],
    ["office", "משרד", "מִשְׂרָד"],
    ["meeting", "פגישה", "פְּגִישָׁה"],
    ["project", "פרויקט", "פְּרוֹיֶקְט"],
    ["tradeoff", "פשרה", "פְּשָׁרָה"],
    ["buy-in", "גיוס תמיכה", "גִּיּוּס תְּמִיכָה"],
    ["alignment", "יישור קו", "יִישּׁוּר קַו"],
    ["action item", "סעיף לביצוע", "סְעִיף לְבִיצּוּעַ"],
    ["owner (of a task)", "אחראי", "אַחֲרַאי"],
    ["bandwidth", "קיבולת", "קִיבּוֹלֶת"],
    ["bottleneck", "צוואר בקבוק", "צַוַּאר בַּקְבּוּק"],
    ["scope creep", "זליגת היקף", "זְלִיגַת הֶקֵּף"],
    ["flagship initiative", "יוזמת דגל", "יוֹזְמַת דֶּגֶל"],
    ["implementation gap", "פער יישום", "פַּעַר יִישּׂוּם"],
  ],
  bureaucracy: [
    ["municipality", "עירייה", "עִירִיָּה"],
    ["authority", "רשות", "רְשׁוּת"],
    ["department", "מחלקה", "מַחְלָקָה"],
    ["application", "בקשה", "בַּקָּשָׁה"],
    ["form", "טופס", "טוֹפֶס"],
    ["document", "מסמך", "מִסְמָךְ"],
    ["certificate", "תעודה", "תְּעוּדָה"],
    ["license", "רישיון", "רִישָּׁיוֹן"],
    ["permit", "היתר", "הֶתֵּר"],
    ["registration", "רישום", "רִישּׁוּם"],
    ["ID card", "תעודת זהות", "תְּעוּדַת זֶהוּת"],
    ["residency", "תושבות", "תּוֹשָׁבוּת"],
    ["citizenship", "אזרחות", "אֶזְרָחוּת"],
    ["tax", "מס", "מַס"],
    ["tax return", "דוח מס", "דּוֹחַ מַס"],
    ["property tax", "ארנונה", "אַרְנוֹנָה"],
    ["national insurance", "ביטוח לאומי", "בִּטּוּחַ לְאוּמִּי"],
    ["health fund", "קופת חולים", "קֻפַּת חוֹלִים"],
    ["queue", "תור", "תּוֹר"],
    ["clerk", "פקיד", "פָּקִיד"],
    ["counter", "אשנב", "אַשְׁנָב"],
    ["office hours", "שעות קבלה", "שְׁעוֹת קַבָּלָה"],
    ["appointment in advance", "תור מראש", "תּוֹר מֵרֹאשׁ"],
    ["signature", "חתימה", "חֲתִימָה"],
    ["stamp", "חותמת", "חוֹתֶמֶת"],
    ["notarization", "אישור נוטריוני", "אִישּׁוּר נוֹטָרְיוֹנִי"],
    ["affidavit", "תצהיר", "תַּצְהִיר"],
    ["declaration", "הצהרה", "הַצְהָרָה"],
    ["appeal", "ערעור", "עִרְעוּר"],
    ["complaint", "תלונה", "תְּלוּנָה"],
    ["fine", "קנס", "קְנָס"],
    ["penalty", "עיצום", "עִיצּוּם"],
    ["exemption", "פטור", "פְּטוֹר"],
    ["eligibility", "זכאות", "זַכָּאוּת"],
    ["means test", "מבחן הכנסה", "מִבְחַן הַכְנָסָה"],
    ["approval", "אישור", "אִישּׁוּר"],
    ["rejection", "דחייה", "דְּחִיָּה"],
    ["extension", "הארכה", "הַאֲרָכָה"],
    ["renewal", "חידוש", "חִדּוּשׁ"],
    ["cancellation", "ביטול", "בִּטּוּל"],
    ["transfer", "העברה", "הַעֲבָרָה"],
    ["record", "רישום", "רִישּׁוּם"],
    ["file", "תיק", "תִּיק"],
    ["reference number", "מספר אסמכתא", "מִסְפַּר אַסְמַכְתָּא"],
    ["copy", "עותק", "עוֹתֶק"],
    ["certified copy", "העתק מאושר", "הֶעְתֵּק מְאוּשָּׁר"],
    ["sworn translation", "תרגום נוטריוני", "תַּרְגּוּם נוֹטָרְיוֹנִי"],
    ["queue number", "מספר תור", "מִסְפַּר תּוֹר"],
    ["waiting period", "תקופת המתנה", "תְּקוּפַת הַמְתָּנָה"],
    ["processing time", "זמן טיפול", "זְמַן טִפּוּל"],
    ["backlog", "פיגור בטיפול", "פִּגּוּר בְּטִפּוּל"],
    ["public inquiry", "פנייה ציבורית", "פְּנִיָּה צִבּוּרִית"],
    ["hotline", "מוקד טלפוני", "מוֹקֵד טֵלֵפוֹנִי"],
    ["ombudsman", "נציב תלונות הציבור", "נְצִיב תְּלוּנוֹת הַצִּבּוּר"],
    ["hearing", "שימוע", "שִׁמּוּעַ"],
    ["summons", "זימון", "זִימּוּן"],
    ["warrant", "צו", "צַו"],
    ["ordinance", "תקנה עירונית", "תַּקָּנָה עִירוֹנִית"],
    ["regulation", "תקנה", "תַּקָּנָה"],
    ["law", "חוק", "חוֹק"],
    ["amendment", "תיקון לחוק", "תִּיקּוּן לַחוֹק"],
    ["enforcement", "אכיפה", "אֲכִיפָה"],
    ["inspector", "מפקח", "מְפַקֵּחַ"],
    ["compliance certificate", "אישור התאמה", "אִישּׁוּר הַתְאָמָה"],
    ["planning permission", "היתר בנייה", "הֶתֵּר בְּנִיָּה"],
    ["zoning", "תכנון ובנייה", "תִּכְנוּן וּבְנִיָּה"],
    ["land registry", "טאבו", "טַאבוּ"],
    ["deed", "נסח טאבו", "נְסַח טַאבוּ"],
    ["power of attorney", "ייפוי כוח", "יִפּוּי כֹּחַ"],
    ["probate order", "צו ירושה", "צַו יְרוּשָּׁה"],
    ["guardianship", "אפוטרופסות", "אַפּוֹטְרוֹפְּסוּת"],
    ["social worker", "עובד סוציאלי", "עוֹבֵד סוֹצְיָאלִי"],
    ["benefits", "קצבאות", "קִצְבָּאוֹת"],
    ["unemployment benefits", "דמי אבטלה", "דְּמֵי אַבְטָלָה"],
    ["maternity leave", "חופשת לידה", "חוּפֶשֶׁת לֵידָה"],
    ["sick leave", "ימי מחלה", "יְמֵי מַחֲלָה"],
    ["labor office", "לשכת התעסוקה", "לִשְׁכַּת הַתַּעֲסוּקָה"],
    ["immigration office", "רשות ההגירה", "רְשׁוּת הַהַגִּירָה"],
    ["border control", "ביקורת גבולות", "בִּקּוֹרֶת גְּבוּלוֹת"],
    ["customs", "מכס", "מֶכֶס"],
    ["declaration form", "טופס הצהרה", "טוֹפֶס הַצְהָרָה"],
    ["import duty", "מס יבוא", "מַס יִיבּוּא"],
    ["export license", "רישיון יצוא", "רִישָּׁיוֹן יִיצּוּא"],
    ["legal aid", "סיוע משפטי", "סִיּוּעַ מִשְׁפָּטִי"],
    ["court", "בית משפט", "בֵּית מִשְׁפָּט"],
    ["legal proceeding", "הליך משפטי", "הֲלִיךְ מִשְׁפָּטִי"],
    ["passport", "דרכון", "דַּרְכּוֹן"],
    ["visa", "ויזה", "וִיזָה"],
  ],
  home_everyday_life: [
    ["shelf", "מדף", "מַדָּף"],
    ["drawer", "מגירה", "מְגִירָה"],
    ["cabinet", "ארון", "אָרוֹן"],
    ["wall cabinet", "ארון קיר", "אֲרוֹן קִיר"],
    ["wardrobe", "ארון בגדים", "אֲרוֹן בְּגָדִים"],
    ["bookcase", "כוננית ספרים", "כוֹנָנִית סְפָרִים"],
    ["dresser", "שידה", "שִׁדָּה"],
    ["nightstand", "שידת לילה", "שִׁדַּת לַיְלָה"],
    ["closet", "ארון קיר", "אֲרוֹן קִיר"],
    ["storage compartment", "תא אחסון", "תָּא אִחְסוּן"],
    ["countertop", "משטח עבודה", "מִשְׁטַח עֲבוֹדָה"],
    ["pantry", "מזווה", "מַזְוֶה"],
    ["laundry room", "חדר כביסה", "חֶדֶר כְּבִיסָה"],
    ["utility room", "חדר שירות", "חֶדֶר שֵׁרוּת"],
    ["entryway", "מבואה", "מָבוֹאָה"],
    ["hallway", "מסדרון", "מִסְדְּרוֹן"],
    ["balcony", "מרפסת", "מִרְפֶּסֶת"],
    ["backyard", "חצר אחורית", "חָצֵר אֲחוֹרִית"],
    ["fence", "גדר", "גָּדֵר"],
    ["gate", "שער", "שַׁעַר"],
    ["lock", "מנעול", "מַנְעוּל"],
    ["spare key", "מפתח רזרבי", "מַפְתֵּחַ רֶזֶרְבִּי"],
    ["doorknob", "ידית דלת", "יְדִית דֶּלֶת"],
    ["door hinge", "ציר דלת", "צִיר דֶּלֶת"],
    ["doorframe", "משקוף", "מַשְׁקוֹף"],
    ["window frame", "מסגרת חלון", "מִסְגֶּרֶת חַלּוֹן"],
    ["windowsill", "אדן חלון", "אֶדֶן חַלּוֹן"],
    ["blind (window)", "תריס", "תְּרִיס"],
    ["curtain rod", "מוט וילון", "מוֹט וִילוֹן"],
    ["light switch", "מתג תאורה", "מַתֵּג תְּאוּרָה"],
    ["electrical outlet", "שקע חשמל", "שֶׁקַע חַשְׁמַל"],
    ["extension cord", "כבל מאריך", "כֶּבֶל מַאֲרִיךְ"],
    ["power strip", "מפצל חשמל", "מְפַצֵּל חַשְׁמַל"],
    ["circuit breaker", "מפסק זרם", "מַפְסֵק זֶרֶם"],
    ["fuse", "נתיך", "נָתִיךְ"],
    ["flashlight", "פנס", "פַּנָּס"],
    ["battery", "סוללה", "סוֹלְלָה"],
    ["toolbox", "ארגז כלים", "אַרְגַּז כֵּלִים"],
    ["screwdriver", "מברג", "מַבְרֵג"],
    ["wrench", "מפתח שוודי", "מַפְתֵּחַ שְׁוֶדִּי"],
    ["hammer", "פטיש", "פַּטִּישׁ"],
    ["drill", "מקדחה", "מַקְדֵּחָה"],
    ["drill bit", "מקדח", "מַקְדָּח"],
    ["nail", "מסמר", "מַסְמֵר"],
    ["screw", "בורג", "בּוֹרֶג"],
    ["wall plug", "דיבל", "דִּיבֶּל"],
    ["measuring tape", "סרט מדידה", "סֶרֶט מְדִידָה"],
    ["level", "פלס", "פְּלָס"],
    ["maintenance", "תחזוקה", "תַּחְזוּקָה"],
    ["repair", "תיקון", "תִּיקּוּן"],
    ["technician", "טכנאי", "טֶכְנַאי"],
    ["contractor", "קבלן", "קַבְלָן"],
    ["warranty", "אחריות", "אַחֲרָיוּת"],
    ["instruction manual", "מדריך שימוש", "מַדְרִיךְ שִׁמּוּשׁ"],
    ["assembly", "הרכבה", "הַרְכָּבָה"],
    ["to assemble", "להרכיב", "לְהַרְכִּיב"],
    ["to disassemble", "לפרק", "לְפָרֵק"],
    ["leak", "נזילה", "נְזִילָה"],
    ["water damage", "נזקי מים", "נִזְקֵי מַיִם"],
    ["dampness", "לחות", "לַחוּת"],
    ["mold", "עובש", "עוֹבֶשׁ"],
    ["mildew", "טחב", "טַחַב"],
    ["drain", "ניקוז", "נִיקּוּז"],
    ["drainpipe", "צינור ניקוז", "צִנּוֹר נִיקּוּז"],
    ["clog", "סתימה", "סְתִימָה"],
    ["plunger", "פומפה", "פּוֹמְפָּה"],
    ["water pressure", "לחץ מים", "לַחַץ מַיִם"],
    ["insulation", "בידוד", "בִּידּוּד"],
    ["air conditioner", "מזגן", "מַזְגָּן"],
    ["heater", "תנור חימום", "תַּנּוּר חִמּוּם"],
    ["radiator", "רדיאטור", "רַדְיָאטוֹר"],
    ["boiler", "דוד", "דּוּד"],
    ["water heater", "דוד מים", "דּוּד מַיִם"],
    ["thermostat", "תרמוסטט", "תֶּרְמוֹסְטָט"],
    ["air purifier", "מטהר אוויר", "מְטַהֵר אֲוִיר"],
    ["dehumidifier", "סופח לחות", "סוֹפֵחַ לַחוּת"],
    ["humidifier", "מכשיר אדים", "מַכְשִׁיר אֵדִים"],
    ["vacuum cleaner", "שואב אבק", "שׁוֹאֵב אָבָק"],
    ["mop", "מגב", "מַגֵּב"],
    ["bucket", "דלי", "דְּלִי"],
    ["broom", "מטאטא", "מַטְאֲטֵא"],
    ["dustpan", "יעה", "יַעָה"],
    ["rag", "סמרטוט", "סְמַרְטוּט"],
    ["detergent", "חומר ניקוי", "חוֹמֶר נִיקּוּי"],
    ["disinfectant", "חומר חיטוי", "חוֹמֶר חִטּוּי"],
    ["bleach", "אקונומיקה", "אקונומיקה"],
    ["to whiten", "להלבין", "לְהַלְבִּין"],
    ["stain remover", "מסיר כתמים", "מֵסִיר כְּתָמִים"],
    ["laundry basket", "סל כביסה", "סַל כְּבִיסָה"],
    ["hamper", "סל כביסה", "סַל כְּבִיסָה"],
    ["clutter", "בלגן", "בַּלְגָּן"],
    ["to declutter", "לסדר ולמיין", "לְסַדֵּר וּלְמַיֵּן"],
    ["recycling bin", "פח מיחזור", "פַּח מִחְזוּר"],
    ["garbage disposal", "פינוי אשפה", "פִּנּוּי אַשְׁפָּה"],
    ["utility bill", "חשבון שירותים", "חֶשְׁבּוֹן שֵׁרוּתִים"],
    ["rent increase", "העלאת שכר דירה", "הַעֲלָאַת שְׂכַר דִּירָה"],
    ["tenancy agreement", "חוזה שכירות", "חוֹזֶה שְׂכִירוּת"],
    ["landlord", "בעל הדירה", "בַּעַל הַדִּירָה"],
    ["tenant", "שוכר", "שׂוֹכֵר"],
    ["building maintenance fee", "ועד בית", "וַעַד בַּיִת"],
    ["to crack your knuckles", "לעשות קנאקים באצבעות", "לַעֲשׂוֹת קְנָאקִים בָּאֶצְבָּעוֹת"],
    ["knuckle", "מפרק אצבע", "מִפְרַק אֶצְבַּע"],
    ["joint", "מפרק", "מִפְרָק"],
    ["to crack one's joints", "לעשות קנאקים", "לַעֲשׂוֹת קְנָאקִים"],
  ],
  abstract_philosophy: [
    ["consciousness", "תודעה", "תּוֹדָעָה"],
    ["identity", "זהות", "זְהוּת"],
    ["perception", "תפיסה", "תְּפִיסָה"],
    ["interpretation", "פרשנות", "פֵּרְשָׁנוּת"],
    ["narrative", "נרטיב", "נָרָטִיב"],
    ["contradiction", "סתירה", "סְתִירָה"],
    ["paradox", "פרדוקס", "פָּרָדוֹקְס"],
    ["ambiguity", "עמימות", "עֲמִימוּת"],
    ["implication", "השלכה", "הַשְׁלָכָה"],
    ["framework", "מסגרת מחשבתית", "מִסְגֶּרֶת מַחְשַׁבְתִּית"],
    ["bias", "הטיה", "הֲטָיָה"],
    ["legitimacy", "לגיטימיות", "לְגִיטִימִיּוּת"],
  ],
  emotional_nuance: [
    ["resentment", "טינה", "טִינָה"],
    ["envy", "קנאה", "קִנְאָה"],
    ["guilt", "אשמה", "אַשְׁמָה"],
    ["shame", "בושה", "בּוּשָׁה"],
    ["relief", "הקלה", "הֲקָלָה"],
    ["disappointment", "אכזבה", "אַכְזָבָה"],
    ["frustration", "תסכול", "תִּסְכּוּל"],
    ["overwhelm", "הצפה", "הצפה"],
    ["vulnerability", "פגיעות", "פְּגִיעוּת"],
    ["attachment", "התקשרות", "התקשרות"],
    ["closing the loop", "סגירת מעגל", "סְגִירַת מַעְגָּל"],
    ["longing", "געגוע", "גַּעְגּוּעַ"],
    ["compassion", "חמלה", "חֶמְלָה"],
    ["grief", "אבל", "אֵבֶל"],
    ["insecurity", "חוסר ביטחון", "חֹסֶר בִּטָּחוֹן"],
    ["trust", "אמון", "אֱמוּן"],
    ["emotional numbness", "קהות רגשית", "קְהוּת רִגְשִׁית"],
    ["vigilance", "דריכות", "דְּרִיכוּת"],
    ["moving on", "להמשיך הלאה", "לְהַמְשִׁיךְ הָלְאָה"],
    ["to let go", "לשחרר", "לְשַׁחְרֵר"],
    ["emotional baggage", "מטען רגשי", "מַטָּעָן רִגְשִׁי"],
    ["to dwell on", "להיתקע על", "לְהִיתָּקַע עַל"],
    ["to spiral", "להיכנס לסחרור", "לְהִיכָּנֵס לְסִחְרוּר"],
  ],
  conversation_glue: [
    ["by the way", "אגב", "אַגַּב"],
    ["technically", "טכנית", "טֶכְנִית"],
    ["in theory", "בתיאוריה", "בְּתֵאוֹרְיָה"],
    ["in practice", "בפועל", "בְּפוֹעַל"],
    ["to be honest", "למען האמת", "לְמַעַן הָאֱמֶת"],
    ["frankly", "בכנות", "בְּכֵנוּת"],
    ["basically", "בעצם", "בְּעֶצֶם"],
    ["sort of", "סוג של", "סוּג שֶׁל"],
    ["roughly speaking", "בגדול", "בְּגָדוֹל"],
    ["the point is", "העניין הוא", "הָעִנְיָן הוּא"],
    ["at the end of the day", "בסופו של דבר", "בְּסוֹפוֹ שֶׁל דָּבָר"],
    ["it depends", "תלוי", "תָּלוּי"],
    ["fair enough", "מקובל", "מְקוּבָּל"],
    ["actually", "בעצם", "בְּעֶצֶם"],
    ["actually", "למעשה", "לְמַעֲשֶׂה"],
    ["like (filler)", "כאילו", "כְּאִילּוּ"],
    ["apparently", "כנראה", "כַּנִּרְאֶה"],
    ["supposedly", "כביכול", "כִּבְיָכוֹל"],
    ["all of a sudden", "פתאום", "פִּתְאוֹם"],
    ["I mean", "כלומר", "כְּלוֹמַר"],
    ["whatever", "לא משנה", "לֹא מְשַׁנֶּה"],
    ["whatever", "שיהיה", "שֶׁיִּהְיֶה"],
  ],
  legal_civic: [
    ["constitution", "חוקה", "חֻקָּה"],
    ["jurisdiction", "סמכות שיפוט", "סַמְכוּת שִׁפּוּט"],
    ["due process", "הליך הוגן", "הֲלִיךְ הוֹגֵן"],
    ["liability", "אחריות משפטית", "אַחֲרָיוּת מִשְׁפָּטִית"],
    ["negligence", "רשלנות", "רַשְׁלָנוּת"],
    ["precedent", "תקדים", "תַּקְדִּים"],
    ["subpoena", "צו זימון", "צַו זִימּוּן"],
    ["injunction", "צו מניעה", "צַו מְנִיעָה"],
    ["civil rights", "זכויות אזרח", "זְכֻיּוֹת אֶזְרָח"],
    ["national security", "ביטחון לאומי", "בִּטָּחוֹן לְאוּמִּי"],
  ],
  technology_ai: [
    ["algorithm", "אלגוריתם", "אַלְגוֹרִיתְם"],
    ["dataset", "מאגר נתונים", "מַאֲגַר נְתוּנִים"],
    ["training data", "נתוני אימון", "נְתוּנֵי אִמּוּן"],
    ["model", "מודל", "מוֹדֶל"],
    ["neural network", "רשת עצבית", "רֶשֶׁת עַצַּבִּית"],
    ["inference", "הסקה", "הַסָּקָה"],
    ["deployment", "הטמעה", "הַטְמָעָה"],
    ["scalability", "מדרגיות", "מִדְרָגִיּוּת"],
    ["open-source", "קוד פתוח", "קוֹד פָּתוּחַ"],
    ["frontier model", "מודל חזית", "מוֹדֶל חֲזִית"],
    ["autonomous system", "מערכת אוטונומית", "מַעֲרֶכֶת אוֹטוֹנוֹמִית"],
    ["recursive improvement", "שיפור רקורסיבי", "שִׁפּוּר רֶקוּרְסִיבִּי"],
    ["prompt", "פרומפט", "פְּרוֹמְפְּט"],
    ["token", "טוקן", "טוֹקֶן"],
    ["context window", "חלון הקשר", "חַלּוֹן הֶקְשֵׁר"],
    ["agent", "סוכן", "סוֹכֵן"],
    ["to fine-tune", "לכוונן", "לְכַוְנֵן"],
    ["benchmark", "בנצ'מרק", "בֶּנְצְ׳מַרְק"],
    ["model collapse", "קריסת מודל", "קְרִיסַת מוֹדֶל"],
    ["safety guardrail", "מנגנון בטיחות", "מַנְגָּנוֹן בְּטִיחוּת"],
    ["reasoning", "הסקה", "הַסָּקָה"],
    ["open weights", "משקלים פתוחים", "מִשְׁקָלִים פְּתוּחִים"],
  ],
  finance_investing: [
    ["portfolio", "תיק השקעות", "תִּיק הַשְׁקָעוֹת"],
    ["asset allocation", "הקצאת נכסים", "הַקְצָאַת נְכָסִים"],
    ["volatility", "תנודתיות", "תְּנוּדָתִיּוּת"],
    ["dividend", "דיבידנד", "דִּיבִידֶנְד"],
    ["bond", "אג\"ח", "אג\"ח"],
    ["liquidity", "נזילות", "נְזִילוּת"],
    ["inflation", "אינפלציה", "אִינְפְלַצְיָה"],
    ["interest rate", "ריבית", "רִיבִּית"],
    ["hedge", "גידור", "גִּידּוּר"],
    ["capital gains", "רווחי הון", "רִוְחֵי הוֹן"],
  ],
  social_cultural: [
    ["secular", "חילוני", "חִילּוֹנִי"],
    ["traditional", "מסורתי", "מָסוֹרְתִּי"],
    ["religious", "דתי", "דָּתִי"],
    ["ultra-Orthodox", "חרדי", "חֲרֵדִי"],
    ["draft exemption", "פטור מגיוס", "פְּטוֹר מִגִּיּוּס"],
    ["protest", "מחאה", "מְחָאָה"],
    ["demonstration", "הפגנה", "הַפְגָּנָה"],
    ["coalition", "קואליציה", "קוֹאָלִיצְיָה"],
    ["opposition", "אופוזיציה", "אוֹפּוֹזִיצְיָה"],
    ["polarization", "קיטוב", "קִטּוּב"],
    ["social gap", "פער חברתי", "פַּעַר חֶבְרָתִי"],
    ["cost of living", "יוקר המחיה", "יוֹקֶר הַמִּחְיָה"],
    ["periphery", "פריפריה", "פְּרִיפֶרְיָה"],
    ["integration", "השתלבות", "הִשְׁתַּלְּבוּת"],
    ["communal solidarity", "סולידריות קהילתית", "סוֹלִידָרִיּוּת קְהִילָּתִית"],
    ["public discourse", "שיח ציבורי", "שִׂיחַ צִבּוּרִי"],
    ["joke", "בדיחה", "בְּדִיחָה"],
    ["lioness", "לביאה", "לְבִיאָה"],
  ],
  dating_relationships: [
    ["chemistry", "כימיה", "כִּימְיָה"],
    ["commitment", "מחויבות", "מְחֻיָּבוּת"],
    ["mixed signals", "מסרים מעורבים", "מְסָרִים מְעוֹרָבִים"],
    ["boundaries", "גבולות", "גְּבוּלוֹת"],
    ["exclusive", "בלעדי", "בִּלְעָדִי"],
    ["long-distance", "מערכת יחסים מרחוק", "מַעֲרֶכֶת יְחָסִים מֵרָחוֹק"],
    ["to ghost", "להיעלם", "לְהֵיעָלֵם"],
    ["to define the relationship", "להגדיר את הקשר", "לְהַגְדִּיר אֶת הַקֶּשֶׁר"],
    ["red flag", "דגל אדום", "דֶּגֶל אָדוֹם"],
    ["green flag", "דגל ירוק", "דֶּגֶל יָרוֹק"],
    ["emotional availability", "זמינות רגשית", "זְמִינוּת רִגְשִׁית"],
    ["shared future", "עתיד משותף", "עָתִיד מְשֻׁתָּף"],
    ["dating fatigue", "עייפות מדייטים", "עֲיֵפוּת מִדֵּיְיטִים"],
    ["to set boundaries", "להציב גבולות", "לְהַצִּיב גְּבוּלוֹת"],
    ["to open up emotionally", "להיפתח רגשית", "לְהִפָּתֵחַ רִגְשִׁית"],
    ["mutual respect", "כבוד הדדי", "כָּבוֹד הֲדָדִי"],
    ["situationship", "קשר לא מוגדר", "קֶשֶׁר לֹא מֻגְדָּר"],
    ["to lead someone on", "למשוך מישהו", "לִמְשֹׁךְ מִישֶׁהוּ"],
    ["to catch feelings", "לפתח רגשות", "לְפַתֵּחַ רְגָשׁוֹת"],
    ["to be hung up on someone", "להיות תקוע על מישהו", "לִהְיוֹת תָּקוּעַ עַל מִישֶׁהוּ"],
    ["to lose interest", "לאבד עניין", "לְאַבֵּד עִנְיָן"],
    ["to get attached", "להיקשר", "לְהִיקָּשֵׁר"],
    ["to pull away", "להתרחק", "לְהִתְרַחֵק"],
    ["to make it official", "להפוך את זה לרשמי", "לַהֲפוֹךְ אֶת זֶה לְרִשְׁמִי"],
  ],
  meta_language: [
    ["root (linguistic)", "שורש", "שֹׁרֶשׁ"],
    ["binyan", "בניין", "בִּנְיָן"],
    ["conjugation", "נטייה", "נְטִיָּה"],
    ["tense", "זמן דקדוקי", "זְמַן דִּקְדּוּקִי"],
    ["nuance", "ניואנס", "נִיוּאַנְס"],
    ["idiom", "ניב", "נִיב"],
    ["slang", "סלנג", "סְלֶנְג"],
    ["literal meaning", "משמעות מילולית", "מַשְׁמָעוּת מִילּוּלִית"],
    ["figurative meaning", "משמעות מושאלת", "מַשְׁמָעוּת מֻשְׁאָלֶת"],
    ["participle", "בינוני", "בֵּינוֹנִי"],
    ["infinitive", "שם הפועל", "שֵׁם הַפּוֹעַל"],
    ["imperative", "ציווי", "צִוּוּי"],
    ["grammatical gender", "מין דקדוקי", "מִין דִּקְדּוּקִי"],
    ["singular", "יחיד", "יָחִיד"],
    ["plural", "רבים", "רַבִּים"],
    ["construct state", "סמיכות", "סְמִיכוּת"],
    ["preposition", "מילת יחס", "מִלַּת יַחַס"],
    ["possessive suffix", "כינוי שייכות", "כִּנּוּי שַׁיָּכוּת"],
    ["direct object marker", "מילת המושא", "מִלַּת הַמּוּשָׂא"],
  ],
  scientific_analytical: [
    ["hypothesis", "השערה", "הַשְׁעָרָה"],
    ["methodology", "מתודולוגיה", "מֵתוֹדוֹלוֹגְיָה"],
    ["variable", "משתנה", "מִשְׁתַּנֶּה"],
    ["correlation", "מתאם", "מִתְאָם"],
    ["causation", "סיבתיות", "סִיבָתִיּוּת"],
    ["margin of error", "טווח טעות", "טְוַח טָעוּת"],
    ["sample size", "גודל מדגם", "גּוֹדֶל מִדְגָּם"],
    ["peer review", "ביקורת עמיתים", "בִּקּוֹרֶת עֲמִיתִים"],
  ],
  abstract_concepts_expanded: [
    ["abstract concept", "מושג מופשט", "מושג מופשט"],
    ["premise", "הנחת יסוד", "הנחת יסוד"],
    ["deduction", "הסקה דדוקטיבית", "הַסָּקָה דדוקטיבית"],
    ["induction", "הסקה אינדוקטיבית", "הַסָּקָה אינדוקטיבית"],
    ["counterargument", "טיעון נגד", "טיעון נגד"],
    ["concession", "הסתייגות", "הסתייגות"],
    ["qualification", "סייג", "סייג"],
    ["certainty", "ודאות", "ודאות"],
    ["uncertainty", "אי-ודאות", "אי-ודאות"],
    ["probability", "הסתברות", "הִסְתַּבְּרוּת"],
    ["risk assessment", "הערכת סיכון", "הַעֲרָכַת סִיכּוּן"],
    ["rhetorical question", "שאלה רטורית", "שאלה רטורית"],
    ["persuasion", "שכנוע", "שכנוע"],
    ["stance", "עמדה", "עמדה"],
    ["thesis statement", "טענת תזה", "טענת תזה"],
    ["emphasis", "הדגשה", "הדגשה"],
  ],
  emotional_psychological_expanded: [
    ["self-awareness", "מודעות עצמית", "מוּדָעוּת עַצְמִית"],
    ["emotional regulation", "ויסות רגשי", "ויסות רגשי"],
    ["burnout", "שחיקה", "שחיקה"],
    ["anxiety disorder", "הפרעת חרדה", "הפרעת חֲרָדָה"],
    ["trauma response", "תגובת טראומה", "תגובת טראומה"],
    ["recovery process", "תהליך החלמה", "תהליך החלמה"],
    ["attachment style", "סגנון התקשרות", "סגנון התקשרות"],
    ["boundary violation", "הפרת גבול", "הפרת גבול"],
    ["autonomy", "אוטונומיה", "אוטונומיה"],
    ["motivation", "מוטיבציה", "מוטיבציה"],
    ["discipline", "משמעת", "משמעת"],
    ["resentment buildup", "הצטברות טינה", "הצטברות טִינָה"],
    ["empathy fatigue", "עייפות אמפתית", "עייפות אמפתית"],
    ["power struggle", "מאבק כוח", "מאבק כוח"],
    ["manipulation", "מניפולציה", "מניפולציה"],
    ["reassurance", "הרגעה", "הרגעה"],
  ],
  relationships_dating_expanded: [
    ["attraction", "משיכה", "משיכה"],
    ["flirtation", "פלרטוט", "פלרטוט"],
    ["compatibility", "התאמה", "הַתְאָמָה"],
    ["exclusivity", "בלעדיות", "בלעדיות"],
    ["commitment issue", "קושי במחויבות", "קושי במחויבות"],
    ["breakup", "פרידה", "פרידה"],
    ["closure conversation", "שיחת סגירה", "שיחת סגירה"],
    ["long-distance relationship", "קשר מרחוק", "קשר מֵרָחוֹק"],
    ["trust issue", "בעיית אמון", "בעיית אֱמוּן"],
    ["red flag behavior", "התנהגות דגל אדום", "התנהגות דֶּגֶל אָדוֹם"],
    ["green flag behavior", "התנהגות דגל ירוק", "התנהגות דֶּגֶל יָרוֹק"],
    ["shared values", "ערכים משותפים", "ערכים משותפים"],
    ["co-parenting", "הורות משותפת", "הורות משותפת"],
    ["in-laws", "מחותנים", "מחותנים"],
    ["extended family", "משפחה מורחבת", "משפחה מורחבת"],
    ["reconciliation", "פיוס", "פיוס"],
  ],
  politics_society_expanded: [
    ["governance", "ממשל", "ממשל"],
    ["public policy", "מדיניות ציבורית", "מְדִינִיּוּת ציבורית"],
    ["election campaign", "קמפיין בחירות", "קַמְפֵּיְין בחירות"],
    ["ballot box", "קלפי", "קַלְפִּי"],
    ["voter turnout", "אחוז הצבעה", "אָחוּז הצבעה"],
    ["coalition agreement", "הסכם קואליציוני", "הסכם קואליציוני"],
    ["opposition bloc", "גוש אופוזיציה", "גוש אוֹפּוֹזִיצְיָה"],
    ["protest movement", "תנועת מחאה", "תנועת מְחָאָה"],
    ["civil rights", "זכויות אזרח", "זְכֻיּוֹת אֶזְרָח"],
    ["secularism", "חילוניות", "חילוניות"],
    ["geopolitics", "גאופוליטיקה", "גאופוליטיקה"],
    ["national resilience", "חוסן לאומי", "חוסן לאומי"],
    ["media bias", "הטיה תקשורתית", "הֲטָיָה תקשורתית"],
    ["investigative journalism", "עיתונות חוקרת", "עיתונות חוקרת"],
    ["polarization", "קיטוב", "קִטּוּב"],
    ["identity politics", "פוליטיקת זהויות", "פוליטיקת זהויות"],
    ["to oust", "להדיח", "לְהַדִּיחַ"],
    ["term in office", "קדנציה", "קַדֶנְצְיָה"],
  ],
  law_legal_systems_expanded: [
    ["constitutional law", "משפט חוקתי", "מִשְׁפָּט חוקתי"],
    ["criminal offense", "עבירה פלילית", "עבירה פלילית"],
    ["indictment", "כתב אישום", "כתב אישום"],
    ["plea bargain", "הסדר טיעון", "הסדר טיעון"],
    ["civil lawsuit", "תביעה אזרחית", "תביעה אזרחית"],
    ["damages", "פיצויים", "פיצויים"],
    ["contract breach", "הפרת חוזה", "הפרת חוֹזֶה"],
    ["liability clause", "סעיף אחריות", "סעיף אַחֲרָיוּת"],
    ["burden of proof", "נטל ההוכחה", "נטל ההוכחה"],
    ["admissible evidence", "ראיה קבילה", "רְאָיָה קבילה"],
    ["cross-examination", "חקירה נגדית", "חקירה נגדית"],
    ["injunction order", "צו מניעה", "צַו מְנִיעָה"],
    ["immigration status", "מעמד הגירה", "מעמד הגירה"],
    ["property deed", "שטר בעלות", "שטר בעלות"],
    ["regulatory compliance", "ציות רגולטורי", "צִיּוּת רגולטורי"],
    ["corporate bylaw", "תקנון חברה", "תקנון חברה"],
  ],
  technology_ai_expanded: [
    ["machine learning", "למידת מכונה", "למידת מכונה"],
    ["supervised learning", "למידה מונחית", "למידה מונחית"],
    ["unsupervised learning", "למידה לא מונחית", "למידה לא מונחית"],
    ["neural layer", "שכבה עצבית", "שכבה עַצַּבִּית"],
    ["fine-tuning", "כוונון עדין", "כוונון עדין"],
    ["prompt engineering", "הנדסת פרומפטים", "הנדסת פרומפטים"],
    ["hallucination (AI)", "הזיה של מודל", "הזיה שֶׁל מוֹדֶל"],
    ["vector database", "מסד נתונים וקטורי", "מסד נְתוּנִים וקטורי"],
    ["encryption", "הצפנה", "הצפנה"],
    ["cybersecurity breach", "פרצת סייבר", "פרצת סייבר"],
    ["privacy policy", "מדיניות פרטיות", "מְדִינִיּוּת פְּרָטִיּוּת"],
    ["surveillance", "מעקב", "מעקב"],
    ["open-source license", "רישיון קוד פתוח", "רִישָּׁיוֹן קוֹד פָּתוּחַ"],
    ["robotics", "רובוטיקה", "רובוטיקה"],
    ["software release", "גרסת תוכנה", "גרסת תוכנה"],
    ["product roadmap", "מפת דרכים למוצר", "מַפַּת דְּרָכִים למוצר"],
    ["startup runway", "מסלול מזומנים לסטארטאפ", "מסלול מְזוּמָנִים לסטארטאפ"],
    ["venture capital", "הון סיכון", "הוֹן סִיכּוּן"],
  ],
  business_finance_expanded: [
    ["cash flow", "תזרים מזומנים", "תַּזְרִים מְזוּמָנִים"],
    ["balance sheet", "מאזן", "מאזן"],
    ["profit margin", "שולי רווח", "שולי רווח"],
    ["revenue forecast", "תחזית הכנסות", "תַּחֲזִית הַכְנָסוֹת"],
    ["valuation", "שווי", "שְׁוִי"],
    ["merger", "מיזוג", "מִיזּוּג"],
    ["acquisition", "רכישה", "רְכִישָׁה"],
    ["due diligence", "בדיקת נאותות", "בְּדִיקַת נאותות"],
    ["shareholder", "בעל מניות", "בַּעַל מְנָיוֹת"],
    ["board of directors", "דירקטוריון", "דִּירֶקְטוֹרְיוֹן"],
    ["macroeconomic trend", "מגמה מאקרו-כלכלית", "מְגַמָּה מאקרו-כלכלית"],
    ["microeconomic incentive", "תמריץ מיקרו-כלכלי", "תמריץ מיקרו-כלכלי"],
    ["mortgage", "משכנתה", "משכנתה"],
    ["insurance premium", "פרמיית ביטוח", "פרמיית ביטוח"],
    ["tax deduction", "ניכוי מס", "ניכוי מַס"],
    ["credit score", "דירוג אשראי", "דירוג אשראי"],
    ["bond yield", "תשואת אגח", "תשואת אגח"],
    ["risk diversification", "פיזור סיכונים", "פיזור סיכונים"],
  ],
  science_research_expanded: [
    ["scientific method", "השיטה המדעית", "השיטה המדעית"],
    ["research design", "תכנון מחקר", "תכנון מחקר"],
    ["control group", "קבוצת ביקורת", "קבוצת ביקורת"],
    ["randomized trial", "ניסוי אקראי", "ניסוי אקראי"],
    ["statistical significance", "מובהקות סטטיסטית", "מובהקות סטטיסטית"],
    ["data analysis", "ניתוח נתונים", "נִיתּוּחַ נְתוּנִים"],
    ["confounding variable", "משתנה מתערב", "מִשְׁתַּנֶּה מתערב"],
    ["replication", "שכפול מחקר", "שכפול מחקר"],
    ["peer-reviewed journal", "כתב עת עם ביקורת עמיתים", "כתב עת עִם ביקורת עמיתים"],
    ["medical protocol", "פרוטוקול רפואי", "פרוטוקול רפואי"],
    ["biological pathway", "מסלול ביולוגי", "מסלול ביולוגי"],
    ["physical law", "חוק פיזיקלי", "חוֹק פיזיקלי"],
    ["chemical reaction", "תגובה כימית", "תגובה כימית"],
    ["environmental impact", "השפעה סביבתית", "השפעה סביבתית"],
    ["climate mitigation", "מיתון אקלים", "מיתון אקלים"],
    ["evidence-based", "מבוסס ראיות", "מבוסס ראיות"],
  ],
  philosophy_intellectual_expanded: [
    ["ethics", "אתיקה", "אתיקה"],
    ["morality", "מוסר", "מוסר"],
    ["epistemology", "אפיסטמולוגיה", "אפיסטמולוגיה"],
    ["metaphysics", "מטאפיזיקה", "מטאפיזיקה"],
    ["free will", "רצון חופשי", "רצון חופשי"],
    ["determinism", "דטרמיניזם", "דטרמיניזם"],
    ["existential question", "שאלה קיומית", "שאלה קיומית"],
    ["consciousness studies", "חקר התודעה", "חקר התודעה"],
    ["identity formation", "גיבוש זהות", "גיבוש זֶהוּת"],
    ["political philosophy", "פילוסופיה פוליטית", "פילוסופיה פוליטית"],
    ["religious philosophy", "פילוסופיה דתית", "פילוסופיה דתית"],
    ["logical fallacy", "כשל לוגי", "כשל לוגי"],
    ["deductive logic", "לוגיקה דדוקטיבית", "לוגיקה דדוקטיבית"],
    ["normative claim", "טענה נורמטיבית", "טענה נורמטיבית"],
    ["moral dilemma", "דילמה מוסרית", "דילמה מוסרית"],
    ["meaning of life", "משמעות החיים", "מַשְׁמָעוּת החיים"],
  ],
  culture_identity_expanded: [
    ["cultural reference", "רפרנס תרבותי", "רפרנס תרבותי"],
    ["holiday ritual", "טקס חג", "טקס חג"],
    ["secular slang", "סלנג חילוני", "סְלֶנְג חִילּוֹנִי"],
    ["military service", "שירות צבאי", "שירות צבאי"],
    ["reserve duty", "שירות מילואים", "שירות מילואים"],
    ["pop culture", "תרבות פופ", "תַּרְבּוּת פופ"],
    ["entertainment industry", "תעשיית הבידור", "תעשיית הבידור"],
    ["music festival", "פסטיבל מוזיקה", "פסטיבל מוזיקה"],
    ["social class", "מעמד חברתי", "מעמד חֶבְרָתִי"],
    ["status symbol", "סמל סטטוס", "סמל סטטוס"],
    ["LGBTQ community", "קהילה להטבית", "קהילה להטבית"],
    ["identity expression", "ביטוי זהות", "ביטוי זֶהוּת"],
    ["religious practice", "פרקטיקה דתית", "פרקטיקה דתית"],
    ["synagogue community", "קהילת בית כנסת", "קהילת בֵּית כנסת"],
    ["cultural assimilation", "הטמעה תרבותית", "הַטְמָעָה תרבותית"],
    ["diaspora identity", "זהות תפוצתית", "זֶהוּת תפוצתית"],
  ],
  communication_mastery_expanded: [
    ["public speaking", "דיבור בפני קהל", "דיבור בפני קהל"],
    ["negotiation tactic", "טקטיקת משא ומתן", "טקטיקת מַשָּׂא וּמַתָּן"],
    ["conflict resolution", "יישוב סכסוכים", "יישוב סכסוכים"],
    ["diplomatic language", "שפה דיפלומטית", "שפה דיפלומטית"],
    ["professional email", "מייל מקצועי", "מייל מקצועי"],
    ["concise writing", "כתיבה תמציתית", "כתיבה תמציתית"],
    ["informal texting", "התכתבות לא פורמלית", "התכתבות לא פורמלית"],
    ["idiomatic expression", "ביטוי אידיומטי", "ביטוי אידיומטי"],
    ["contemporary slang", "סלנג עכשווי", "סְלֶנְג עכשווי"],
    ["sarcasm", "סרקזם", "סרקזם"],
    ["irony", "אירוניה", "אירוניה"],
    ["subtext", "טקסט סמוי", "טקסט סמוי"],
    ["tone of voice", "טון דיבור", "טון דיבור"],
    ["persuasive pitch", "נאום שכנוע", "נאום שכנוע"],
    ["rebuttal", "הפרכה", "הפרכה"],
    ["active listening", "הקשבה פעילה", "הקשבה פעילה"],
  ],
  everyday_survival_expanded: [
    ["apartment viewing", "צפייה בדירה", "צפייה בדירה"],
    ["lease contract", "חוזה שכירות", "חוֹזֶה שְׂכִירוּת"],
    ["utility meter", "מד שירות", "מד שירות"],
    ["electricity bill", "חשבון חשמל", "חשבון חַשְׁמַל"],
    ["water bill", "חשבון מים", "חשבון מַיִם"],
    ["municipal tax", "ארנונה", "אַרְנוֹנָה"],
    ["car registration", "רישוי רכב", "רישוי רכב"],
    ["insurance claim", "תביעת ביטוח", "תביעת ביטוח"],
    ["customer complaint", "תלונת לקוח", "תלונת לָקוֹחַ"],
    ["service representative", "נציג שירות", "נציג שירות"],
    ["emergency repair", "תיקון חירום", "תִּיקּוּן חֵירוּם"],
    ["plumber", "אינסטלטור", "אינסטלטור"],
    ["travel disruption", "שיבוש נסיעה", "שיבוש נסיעה"],
    ["lost luggage", "מזוודה אבודה", "מזוודה אבודה"],
    ["appointment slot", "תור פנוי", "תּוֹר פנוי"],
  ],
  media_digital_life_expanded: [
    ["social media post", "פוסט ברשתות חברתיות", "פוסט ברשתות חברתיות"],
    ["online discourse", "שיח מקוון", "שיח מקוון"],
    ["content creator", "יוצר תוכן", "יוצר תוכן"],
    ["influencer", "משפיען", "משפיען"],
    ["livestream", "שידור חי", "שידור חי"],
    ["streaming platform", "פלטפורמת סטרימינג", "פלטפורמת סטרימינג"],
    ["gaming community", "קהילת גיימינג", "קהילת גיימינג"],
    ["internet slang", "סלנג אינטרנטי", "סְלֶנְג אינטרנטי"],
    ["meme", "מם", "מם"],
    ["viral trend", "טרנד ויראלי", "טרנד ויראלי"],
    ["comment thread", "שרשור תגובות", "שרשור תגובות"],
    ["moderation policy", "מדיניות ניהול תוכן", "מְדִינִיּוּת נִיהוּל תוכן"],
    ["digital footprint", "טביעת רגל דיגיטלית", "טביעת רגל דיגיטלית"],
    ["notification overload", "עומס התראות", "עומס התראות"],
    ["screen time", "זמן מסך", "זְמַן מסך"],
    ["algorithmic feed", "פיד אלגוריתמי", "פיד אלגוריתמי"],
    ["screenshot", "צילום מסך", "צִלּוּם מָסָךְ"],
    ["to scroll", "לגלול", "לִגְלֹל"],
    ["to swipe", "להחליק", "לְהַחְלִיק"],
    ["to tap", "להקיש", "לְהַקִּישׁ"],
    ["to click", "ללחוץ", "לִלְחוֹץ"],
    ["bug", "באג", "בַּאג"],
    ["glitch", "גליץ'", "גְלִיץ׳"],
    ["lag", "לאג", "לַאג"],
    ["update", "עדכון", "עִדְכּוּן"],
    ["settings", "הגדרות", "הַגְדָּרוֹת"],
  ],
  health_body_expanded: [
    ["nutrition plan", "תוכנית תזונה", "תוכנית תְּזוּנָה"],
    ["caloric deficit", "גירעון קלורי", "גירעון קלורי"],
    ["strength training", "אימון כוח", "אימון כוח"],
    ["cardio endurance", "סבולת לב-ריאה", "סבולת לֵב-ריאה"],
    ["sports injury", "פציעת ספורט", "פציעת ספורט"],
    ["chronic condition", "מצב כרוני", "מצב כְּרוֹנִי"],
    ["preventive screening", "בדיקת מנע", "בְּדִיקַת מנע"],
    ["medical referral", "הפניה רפואית", "הַפְנָיָה רפואית"],
    ["insurance dispute", "סכסוך ביטוחי", "סכסוך ביטוחי"],
    ["treatment plan", "תוכנית טיפול", "תוכנית טיפול"],
    ["prescription renewal", "חידוש מרשם", "חידוש מִרְשָׁם"],
    ["side effect", "תופעת לוואי", "תוֹפַעַת לְוַאי"],
    ["rehabilitation", "שיקום", "שִׁקּוּם"],
    ["mental health clinic", "מרפאת בריאות הנפש", "מרפאת בְּרִיאוּת הנפש"],
    ["patient rights", "זכויות מטופל", "זכויות מטופל"],
    ["informed consent", "הסכמה מדעת", "הסכמה מדעת"],
  ],
  advanced_grammar_meta_expanded: [
    ["linguistics terminology", "מונחי בלשנות", "מונחי בלשנות"],
    ["word formation", "תצורת מילים", "תצורת מילים"],
    ["verbal pattern", "תבנית פועל", "תַּבְנִית פועל"],
    ["nominal pattern", "תבנית שם", "תַּבְנִית שם"],
    ["language register", "משלב לשוני", "משלב לשוני"],
    ["formal register", "משלב רשמי", "משלב רשמי"],
    ["informal register", "משלב לא רשמי", "משלב לא רשמי"],
    ["biblical Hebrew", "עברית מקראית", "עברית מקראית"],
    ["modern Hebrew", "עברית מודרנית", "עברית מודרנית"],
    ["Aramaic influence", "השפעה ארמית", "השפעה ארמית"],
    ["root letter", "אות שורש", "אות שורש"],
    ["weak root", "שורש חלש", "שורש חלש"],
    ["prefix", "תחילית", "תחילית"],
    ["suffix", "סופית", "סופית"],
    ["syntax", "תחביר", "תחביר"],
    ["pragmatics", "פרגמטיקה", "פרגמטיקה"],
  ],
  high_level_discourse_expanded: [
    ["think tank", "מכון מחקר מדיניות", "מכון מחקר מְדִינִיּוּת"],
    ["white paper", "נייר עמדה", "נייר עמדה"],
    ["risk assessment matrix", "מטריצת סיכונים", "מטריצת סיכונים"],
    ["strategic planning", "תכנון אסטרטגי", "תכנון אסטרטגי"],
    ["governance framework", "מסגרת ממשל תאגידי", "מִסְגֶּרֶת ממשל תאגידי"],
    ["institutional capacity", "יכולת מוסדית", "יכולת מוסדית"],
    ["international relations", "יחסים בינלאומיים", "יְחָסִים בינלאומיים"],
    ["security doctrine", "דוקטרינת ביטחון", "דוקטרינת ביטחון"],
    ["scenario planning", "תכנון תרחישים", "תכנון תרחישים"],
    ["early warning indicator", "מדד התרעה מוקדמת", "מַדַּד התרעה מוקדמת"],
    ["technological forecasting", "חיזוי טכנולוגי", "חיזוי טכנולוגי"],
    ["policy recommendation", "המלצת מדיניות", "המלצת מְדִינִיּוּת"],
    ["implementation roadmap", "מפת דרכים ליישום", "מַפַּת דְּרָכִים ליישום"],
    ["stakeholder alignment", "יישור בעלי עניין", "יישור בעלי עניין"],
    ["strategic ambiguity", "עמימות אסטרטגית", "עֲמִימוּת אסטרטגית"],
    ["escalation ladder", "סולם הסלמה", "סולם הסלמה"],
  ],
};

const AVAILABILITY_DEFAULTS = Object.freeze({
  translationQuiz: true,
  sentenceHints: true,
});

const LEXICON_AVAILABILITY_OVERRIDES = new Map([
  ["אחות", { translationQuiz: false }],
  ["בית חולים", { translationQuiz: false }],
  ["כיור", { translationQuiz: false }],
  ["מקרר", { translationQuiz: false }],
  ["סכין", { translationQuiz: false }],
  ["רופא", { translationQuiz: false }],
  ["משרד", { translationQuiz: false }],
  ["פגישה", { translationQuiz: false }],
  ["פרויקט", { translationQuiz: false }],
  ["דרכון", { translationQuiz: false }],
  ["ויזה", { translationQuiz: false }],
]);

function normalizeAvailability(availability) {
  return {
    translationQuiz: availability?.translationQuiz !== false,
    sentenceHints: availability?.sentenceHints !== false,
  };
}

function slug(input) {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
    .slice(0, 80);
}

function getBaseVocabulary() {
  const words = [];

  Object.entries(RAW).forEach(([category, rows], categoryIndex) => {
    const max = rows.length;

    rows.forEach(([en, he, heNiqqud = ""], idx) => {
      const utility = Math.max(1, 100 - Math.floor((idx / max) * 45) - categoryIndex * 2);
      const id = `${category}-${String(idx + 1).padStart(3, "0")}-${slug(en)}`;

      words.push({
        id,
        category,
        en,
        he,
        heNiqqud: heNiqqud || he,
        utility,
        availability: normalizeAvailability(LEXICON_AVAILABILITY_OVERRIDES.get(he) || AVAILABILITY_DEFAULTS),
        source: "seed",
      });
    });
  });

  return words;
}

global.IvriQuestVocab = {
  CATEGORY_META,
  EXPANSION_TRACKS,
  getBaseVocabulary,
  __build: "20260307b",
};
})(typeof window !== "undefined" ? window : globalThis);
