(function initIvriQuestAppBootstrapData(global) {
"use strict";

const app = global.IvriQuestApp = global.IvriQuestApp || {};
const bootstrapData = app.bootstrapData = app.bootstrapData || {};

bootstrapData.buildDomainByCategoryMap = bootstrapData.buildDomainByCategoryMap || function buildDomainByCategoryMap(domains) {
  const categoryMap = new Map();
  domains.forEach((domain) => {
    domain.categories.forEach((category) => {
      categoryMap.set(category, domain.id);
    });
  });
  return categoryMap;
};

bootstrapData.I18N = bootstrapData.I18N || {
  en: {
    app: {
      title: "IvritElite | Advanced Hebrew Trainer",
      name: "IvritElite",
    },
    nav: {
      home: "Home",
      learn: "Learn",
      review: "Review",
      settings: "Settings",
      results: "Results",
    },
    top: {
      eyebrow: "Browser-Only Hebrew Mastery",
      subhead: "Advanced vocabulary trainer inspired by Duolingo, tuned for real-world fluency.",
      accuracy: "Accuracy",
      streak: "Current Streak",
    },
    controls: {
      settings: "Settings",
      interface: "Interface",
      lightMode: "Light Mode",
      darkMode: "Dark Mode",
      reset: "Reset Progress",
      resetConfirm: "Reset all spaced-repetition progress and streak data?",
    },
    perf: {
      eyebrow: "Performance Snapshot",
      title: "Vocabulary Type",
      note: "Since your last progress reset",
    },
    session: {
      eyebrow: "Session",
      mixedTitle: "Translation",
      secondChanceTitle: "Translation Review",
      verbMatchTitle: "Conjugation",
      abbreviationTitle: "Abbreviation",
      round: "Round: {current}/{total}",
      secondChanceProgress: "Second chance: {current}/{total}",
      secondChanceContinue: "Start Second Chance",
      words: "Words: {count}",
      timer: "Time: {seconds}s",
      score: "Score: {score}",
      start: "Start Translation",
      restart: "Restart Translation",
      verbMatchStart: "Start Conjugation",
      verbMatchRestart: "Restart Conjugation",
      abbreviationStart: "Start Abbreviation",
      abbreviationRestart: "Restart Abbreviation",
      nextVerb: "Next Verb",
      skip: "Skip",
      submit: "Submit",
      next: "Next",
      viewResults: "View Results",
      backHome: "Back to Home",
      leaveTitle: "Leave this game?",
      leaveBody: "If you leave this game now, you'll lose your progress so far.",
      keepPlaying: "Keep Playing",
      leaveGame: "Lose Progress",
      starting: "Starting...",
      playAgain: "Play Again",
    },
    home: {
      title: "Choose A Game",
      status: "Pick a mode to start.",
      label: "Homepage",
      prompt: "Choose one of the three game modes below.",
    },
    dashboard: {
      eyebrow: "Daily Focus",
      greeting: "Welcome back",
      lessonsEyebrow: "Lesson Options",
      lessonsTitle: "Choose Your Lesson",
      statsEyebrow: "Stats Summary",
      statsTitle: "Current Snapshot",
      user: "Learner",
      userPlaceholder: "You",
      learned: "Total Vocab Learned",
      modeEyebrow: "Interface",
      modeTitle: "Options",
      continue: "Continue Lesson",
      review: "Review Mistakes",
      settings: "Open Settings",
      ready: "Ready to jump back in.",
      active: "Lesson in progress.",
      idle: "No lesson in progress.",
      activeMode: "Current focus",
      currentMode: "Mode",
      language: "Language",
      theme: "Theme",
      niqqud: "Nikud",
      on: "On",
      off: "Off",
    },
    learn: {
      idleLabel: "Learn",
      idlePrompt: "Pick a mode to start a focused session.",
    },
    game: {
      translationName: "Translation",
      translationNote: "Fast multiple-choice translation rounds.",
      conjugationName: "Conjugation",
      conjugationNote: "Match English forms to Hebrew conjugations.",
      abbreviationName: "Abbreviation",
      abbreviationNote: "Guess English meanings from Hebrew abbreviations.",
      advConjName: "Advanced Conjugation",
      advConjNote: "Conjugate both subject and object of Hebrew verbal idioms.",
    },
    prompt: {
      lesson: "Lesson",
      start: 'Press "Start Translation" to begin.',
      verbMatchStart: 'Press "Start Conjugation" to practice conjugations and root forms.',
      abbreviation: "Abbreviation",
      abbreviationStart: 'Press "Start Abbreviation" to guess meanings and see full Hebrew expansions.',
      noAbbreviationTitle: "No abbreviations loaded",
      noAbbreviationBody: "Ask the agent to update abbreviation-data.js, then reload.",
      noVocabTitle: "No vocabulary loaded",
      noVocabBody: "Ask the agent to update vocab-data.js, then reload.",
      masteredOnlyTitle: "Translation pool is empty",
      masteredOnlyBody: "All words are currently mastered for translation. Reset progress in Settings to restore them.",
      showNiqqud: "Show Nikud",
      hideNiqqud: "Hide Nikud",
      toEnglish: "Translate to English",
      toHebrew: "Translate to Hebrew",
      reviewToEnglish: "Second Chance: Translate to English",
      reviewToHebrew: "Second Chance: Translate to Hebrew",
    },
    audio: {
      label: "Sound Effects",
      on: "On",
      off: "Off",
    },
    feedback: {
      correct: "Correct: {answer}",
      wrong: "Not quite. Correct answer: {answer} ({english})",
      abbreviationCorrect: "Correct: {english} | {expansion}",
      abbreviationWrong: "Not quite. Correct answer: {english} | {expansion}",
      lessonDone: "Lesson complete. Final score {score}/{total}.",
      reviewAdded: "Second chance rounds included: {count}.",
      startAnother: 'Press "Start Translation" to run another round.',
      reviewIntro: "Second chance round: retry {count} words you missed.",
      matchDoneVerb: "Verb complete: {verb}.",
      matchDoneAll: "Conjugation session complete. Verbs covered: {count}.",
      advConjCorrect: "Correct: {answer}",
      advConjWrong: "Not quite. Correct answer: {answer}",
    },
    summary: {
      resultsHeader: "Session Results",
      lessonTitle: "Translation Complete",
      matchTitle: "Conjugation Complete",
      abbreviationTitle: "Abbreviation Complete",
      advConjTitle: "Advanced Conjugation Complete",
      score: "Score: {score}/{total}",
      lessonNote: "Second-chance rounds: {count}",
      lessonNoteNone: "No second-chance rounds this run.",
      matchNote: "Verbs: {verbs} | Best combo: {combo} | Time: {seconds}s",
      abbreviationNote: "Rounds: {rounds} | Time: {seconds}s",
      thumbsText: "Great work",
    },
    review: {
      queueEyebrow: "Revenge Queue",
      queueTitle: "Review Queue",
      queueEmpty: "No review items waiting.",
      pending: "{count} items waiting for revenge mode.",
      empty: "Nothing is waiting in the current review queue.",
      analyticsEyebrow: "Category Analytics",
      analyticsTitle: "Category Performance",
      missedTitle: "Mistakes To Revenge",
    },
    settings: {
      title: "Settings",
      note: "Adjust language, theme, sounds, and inline nikud.",
      language: "Language",
      feedbackSurvey: "Feedback survey",
      niqqud: "Inline Nikud",
      theme: "Theme",
      resetTitle: "Reset Progress",
      resetNote: "Clear saved spacing, streaks, and review data.",
    },
    welcome: {
      title: "Welcome to IvritElite!",
      line1: "This is a new app for advanced Hebrew learning.",
      surveyPrefix: "We would love to hear your feedback in ",
      surveyLink: "this survey",
      surveySuffix: ".",
      line2: "You can also access the survey from the Settings page.",
      close: "Close",
      closeAria: "Close welcome message",
    },
    results: {
      continue: "Play Again",
      correct: "Correct",
      incorrect: "Incorrect",
      time: "Time",
      score: "Score",
      accuracy: "Accuracy",
      reviewRounds: "Review Rounds",
      rounds: "Rounds",
      verbs: "Verbs",
      bestCombo: "Best Combo",
      mistakes: "Session Mistakes",
      reviewPerformance: "Review Performance",
      niceJob: "Nice job!",
      roomToImprove: "There's room to improve",
      amazing: "Amazing!",
      noMistakes: "No mistakes in this session.",
    },
    match: {
      prompt: "Match the pairs",
      verbLabel: "Verb",
      leftColumn: "English",
      rightColumn: "Hebrew",
      progress: "Pairs: {current}/{total}",
      verbProgress: "Verb: {current}/{total}",
      timer: "Time: {seconds}s",
      combo: "Combo x{count}",
      roundDone: "Great. You matched all forms for {verb}.",
      noVerbs: "No verbs found in the vocabulary list.",
      validatedNote: "Using stored validated forms for this verb.",
      generatedNote: "Using validated generated forms for an explicitly safe verb.",
    },
    pool: {
      summary: "Translation pool: {pool} words with nikud ({total} in lexicon).",
      expansion: "Expansion tracks mapped: {count}.",
      tempProgress: "Progress is temporary in this browser mode (storage unavailable).",
      fallback: "Fallback vocab loaded because vocab-data.js was not available.",
    },
    missed: {
      title: "Most Missed",
      note: "Words you have missed most often.",
      empty: "No misses yet.",
      misses: "{count} misses",
    },
    mastered: {
      open: "Mastered List",
      title: "Mastered Words",
      note: "Mastered words are excluded from Translation but still used in Conjugation.",
      selectHint: "Select words to restore to translation testing.",
      empty: "No mastered words yet.",
      restoreSelected: "Restore Selected",
      close: "Close",
      moveCurrent: "Move To Mastered",
      streakStatus: "Clean streak: {count}/{target}",
      ready: "{verb} reached {target} clean rounds. You can move it to Mastered.",
      added: "{word} moved to Mastered.",
      restored: "Restored {count} words to translation.",
    },
    domain: {
      colloquial: "Colloquial & Street",
      everyday: "Everyday Functional",
      professional: "Professional",
      formal: "Formal & Analytical",
    },
  },
  he: {
    app: {
      title: "עברית עילית | מאמן עברית מתקדם",
      name: "עברית עילית",
    },
    nav: {
      home: "בית",
      learn: "לומדים",
      review: "סקירה",
      settings: "הגדרות",
      results: "תוצאות",
    },
    top: {
      eyebrow: "שליטה בעברית בדפדפן בלבד",
      subhead: "מאמן אוצר מילים מתקדם בהשראת Duolingo, מותאם לשטף בשימוש אמיתי.",
      accuracy: "דיוק",
      streak: "רצף נוכחי",
    },
    controls: {
      settings: "הגדרות",
      interface: "ממשק",
      lightMode: "מצב בהיר",
      darkMode: "מצב כהה",
      reset: "איפוס התקדמות",
      resetConfirm: "לאפס את כל התקדמות החזרות והסטטיסטיקות?",
    },
    perf: {
      eyebrow: "תמונת ביצועים",
      title: "סוג אוצר מילים",
      note: "מאז איפוס ההתקדמות האחרון",
    },
    session: {
      eyebrow: "אימון",
      mixedTitle: "תרגום",
      secondChanceTitle: "סבב הזדמנות שנייה",
      verbMatchTitle: "נטיות",
      abbreviationTitle: "קיצורים",
      round: "סבב: {current}/{total}",
      secondChanceProgress: "הזדמנות שנייה: {current}/{total}",
      secondChanceContinue: "התחל הזדמנות שנייה",
      words: "מילים: {count}",
      timer: "זמן: {seconds}ש׳",
      score: "ציון: {score}",
      start: "התחל תרגום",
      restart: "התחל תרגום מחדש",
      verbMatchStart: "התחל נטיות",
      verbMatchRestart: "התחל נטיות מחדש",
      abbreviationStart: "התחל קיצורים",
      abbreviationRestart: "התחל קיצורים מחדש",
      nextVerb: "לפועל הבא",
      skip: "דלג",
      submit: "שלח",
      next: "הבא",
      viewResults: "לתוצאות",
      backHome: "חזרה לעמוד הבית",
      leaveTitle: "לצאת מהמשחק?",
      leaveBody: "אם תצא עכשיו מהמשחק, תאבד את ההתקדמות שלך עד כה.",
      keepPlaying: "להמשיך לשחק",
      leaveGame: "לאבד התקדמות",
      starting: "מתחיל...",
      playAgain: "שחק שוב",
    },
    home: {
      title: "בחר משחק",
      status: "בחר מצב כדי להתחיל.",
      label: "דף הבית",
      prompt: "בחר אחד משלושת מצבי המשחק כאן למטה.",
    },
    dashboard: {
      eyebrow: "פוקוס יומי",
      greeting: "ברוך שובך",
      lessonsEyebrow: "אפשרויות שיעור",
      lessonsTitle: "בחר שיעור",
      statsEyebrow: "סיכום נתונים",
      statsTitle: "תמונת מצב נוכחית",
      user: "לומד",
      userPlaceholder: "אתה",
      learned: "סך אוצר מילים שנלמד",
      modeEyebrow: "ממשק",
      modeTitle: "אפשרויות",
      continue: "המשך שיעור",
      review: "סקור טעויות",
      settings: "פתח הגדרות",
      ready: "מוכן לחזור לתרגול.",
      active: "יש שיעור פעיל.",
      idle: "אין כרגע שיעור פעיל.",
      activeMode: "פוקוס נוכחי",
      currentMode: "מצב",
      language: "שפה",
      theme: "ערכת נושא",
      niqqud: "ניקוד",
      on: "פועל",
      off: "כבוי",
    },
    learn: {
      idleLabel: "לומדים",
      idlePrompt: "בחר מצב כדי להתחיל סשן ממוקד.",
    },
    game: {
      translationName: "תרגום",
      translationNote: "סבבי תרגום מהירים במתכונת בחירה מרובה.",
      conjugationName: "נטיות",
      conjugationNote: "התאם בין נטיות באנגלית לנטיות בעברית.",
      abbreviationName: "ראשי תיבות",
      abbreviationNote: "נחש את המשמעות באנגלית לפי קיצור בעברית.",
      advConjName: "נטיות מתקדמות",
      advConjNote: "נטה גם את הנושא וגם את המושא של ביטויים פועלים עבריים.",
    },
    prompt: {
      lesson: "שיעור",
      start: 'לחץ על "התחל תרגום" כדי להתחיל.',
      verbMatchStart: 'לחץ על "התחל נטיות" כדי לתרגל נטיות ושמות שורש.',
      abbreviation: "קיצור",
      abbreviationStart: 'לחץ על "התחל קיצורים" כדי לנחש משמעות ולקבל את הפירוש המלא.',
      noAbbreviationTitle: "אין קיצורים טעונים",
      noAbbreviationBody: "בקש מהסוכן לעדכן את abbreviation-data.js ואז טען מחדש.",
      noVocabTitle: "אין אוצר מילים טעון",
      noVocabBody: "בקש מהסוכן לעדכן את vocab-data.js ואז טען מחדש.",
      masteredOnlyTitle: "אין מילים זמינות לתרגום",
      masteredOnlyBody: "כל המילים כרגע מנוסות לתרגום. אפס את ההתקדמות בהגדרות כדי להחזיר אותן.",
      showNiqqud: "הצג ניקוד",
      hideNiqqud: "הסתר ניקוד",
      toEnglish: "תרגם לאנגלית",
      toHebrew: "תרגם לעברית",
      reviewToEnglish: "הזדמנות שנייה: תרגם לאנגלית",
      reviewToHebrew: "הזדמנות שנייה: תרגם לעברית",
    },
    audio: {
      label: "אפקטים קוליים",
      on: "פועל",
      off: "כבוי",
    },
    feedback: {
      correct: "נכון: {answer}",
      wrong: "לא מדויק. התשובה הנכונה: {answer} ({english})",
      abbreviationCorrect: "נכון: {english} | {expansion}",
      abbreviationWrong: "לא מדויק. התשובה הנכונה: {english} | {expansion}",
      lessonDone: "השיעור הושלם. ציון סופי {score}/{total}.",
      reviewAdded: "נכללו סבבי הזדמנות שנייה: {count}.",
      startAnother: 'לחץ על "התחל תרגום" כדי להתחיל עוד סבב.',
      reviewIntro: "סבב הזדמנות שנייה: נסה שוב {count} מילים שפספסת.",
      matchDoneVerb: "הפועל הושלם: {verb}.",
      matchDoneAll: "אימון הנטיות הושלם. פעלים שכוסו: {count}.",
      advConjCorrect: "נכון: {answer}",
      advConjWrong: "לא מדויק. התשובה הנכונה: {answer}",
    },
    summary: {
      resultsHeader: "סיכום אימון",
      lessonTitle: "תרגום הושלם",
      matchTitle: "נטיות הושלמו",
      abbreviationTitle: "קיצורים הושלמו",
      advConjTitle: "נטיות מתקדמות הושלמו",
      score: "ציון: {score}/{total}",
      lessonNote: "סבבי הזדמנות שנייה: {count}",
      lessonNoteNone: "בסבב הזה לא היו סבבי הזדמנות שנייה.",
      matchNote: "פעלים: {verbs} | קומבו שיא: {combo} | זמן: {seconds}ש׳",
      abbreviationNote: "סבבים: {rounds} | זמן: {seconds}ש׳",
      thumbsText: "כל הכבוד",
    },
    review: {
      queueEyebrow: "תור נקמה",
      queueTitle: "תור סקירה",
      queueEmpty: "אין פריטים שמחכים כרגע.",
      pending: "{count} פריטים מחכים למצב נקמה.",
      empty: "אין כרגע פריטים בתור הסקירה הפעיל.",
      analyticsEyebrow: "ניתוח קטגוריות",
      analyticsTitle: "ביצועים לפי קטגוריה",
      missedTitle: "טעויות לנקמה",
    },
    settings: {
      title: "הגדרות",
      note: "התאם שפה, ערכת נושא, צלילים וניקוד מובנה.",
      language: "שפה",
      feedbackSurvey: "שאלון משוב",
      niqqud: "ניקוד מובנה",
      theme: "ערכת נושא",
      resetTitle: "איפוס התקדמות",
      resetNote: "נקה שמירות, רצפים ונתוני סקירה.",
    },
    welcome: {
      title: "ברוך הבא ל-IvritElite!",
      line1: "זאת אפליקציה חדשה ללימוד עברית ברמה מתקדמת.",
      surveyPrefix: "נשמח לשמוע את המשוב שלך ב",
      surveyLink: "שאלון הזה",
      surveySuffix: ".",
      line2: "אפשר גם לגשת לשאלון מעמוד ההגדרות.",
      close: "סגור",
      closeAria: "סגור הודעת פתיחה",
    },
    results: {
      continue: "שחק שוב",
      correct: "נכון",
      incorrect: "שגוי",
      time: "זמן",
      score: "ציון",
      accuracy: "דיוק",
      reviewRounds: "סבבי חזרה",
      rounds: "סבבים",
      verbs: "פעלים",
      bestCombo: "הקומבו הטוב ביותר",
      mistakes: "טעויות מהסשן",
      reviewPerformance: "סקירת ביצועים",
      niceJob: "כל הכבוד!",
      roomToImprove: "יש מקום לשיפור",
      amazing: "זה מדהים!",
      noMistakes: "לא היו טעויות בסשן הזה.",
    },
    match: {
      prompt: "התאם בין הזוגות",
      verbLabel: "פועל",
      leftColumn: "אנגלית",
      rightColumn: "עברית",
      progress: "זוגות: {current}/{total}",
      verbProgress: "פועל: {current}/{total}",
      timer: "זמן: {seconds}ש׳",
      combo: "קומבו x{count}",
      roundDone: "מעולה. התאמת את כל הנטיות עבור {verb}.",
      noVerbs: "לא נמצאו פעלים ברשימת אוצר המילים.",
      validatedNote: "נעשה שימוש בצורות מאומתות ושמורות עבור הפועל הזה.",
      generatedNote: "נעשה שימוש בצורות מחוללות ומאומתות עבור פועל שסומן בטוח להפקה.",
    },
    pool: {
      summary: "מאגר התרגום: {pool} מילים עם ניקוד ({total} בלקסיקון).",
      expansion: "מסלולי הרחבה שמופו: {count}.",
      tempProgress: "ההתקדמות זמנית בדפדפן זה (אחסון לא זמין).",
      fallback: "נטען אוצר מילים חלופי כי vocab-data.js לא היה זמין.",
    },
    missed: {
      title: "הלוח שפספסת הכי הרבה",
      note: "המילים שטעית בהן בתדירות הגבוהה ביותר.",
      empty: "עדיין אין פספוסים.",
      misses: "{count} פספוסים",
    },
    mastered: {
      open: "רשימת מנוסות",
      title: "מילים מנוסות",
      note: "מילים מנוסות יוצאות מסבבי תרגום אבל נשארות בסבבי נטיות.",
      selectHint: "סמן מילים שתרצה להחזיר לתרגול תרגום.",
      empty: "אין עדיין מילים מנוסות.",
      restoreSelected: "החזר מסומנות",
      close: "סגור",
      moveCurrent: "העבר למנוסות",
      streakStatus: "רצף נקי: {count}/{target}",
      ready: "הפועל {verb} הגיע ל-{target} סבבים נקיים. אפשר להעביר לרשימת מנוסות.",
      added: "{word} הועבר לרשימת מנוסות.",
      restored: "הוחזרו {count} מילים לתרגול תרגום.",
    },
    domain: {
      colloquial: "דיבורי ורחוב",
      everyday: "יומיומי ופונקציונלי",
      professional: "מקצועי",
      formal: "פורמלי ואנליטי",
    },
  },
};

bootstrapData.PERFORMANCE_DOMAINS = bootstrapData.PERFORMANCE_DOMAINS || [
  {
    id: "colloquial",
    emoji: "🗣️",
    label: "Colloquial & Street",
    categories: new Set([
      "conversation_glue",
      "dating_relationships",
      "relationships_dating_expanded",
      "media_digital_life_expanded",
      "emotional_nuance",
      "emotional_psychological_expanded",
      "social_cultural",
      "culture_identity_expanded",
    ]),
  },
  {
    id: "everyday",
    emoji: "🏠",
    label: "Everyday Functional",
    categories: new Set([
      "cooking_utensils",
      "cooking_verbs",
      "home_everyday_life",
      "everyday_survival_expanded",
      "health",
      "health_body_expanded",
      "bureaucracy",
    ]),
  },
  {
    id: "professional",
    emoji: "💼",
    label: "Professional",
    categories: new Set([
      "work_business",
      "business_finance_expanded",
      "finance_investing",
      "legal_civic",
      "law_legal_systems_expanded",
      "politics_society_expanded",
      "communication_mastery_expanded",
      "technology_ai",
      "technology_ai_expanded",
    ]),
  },
  {
    id: "formal",
    emoji: "📚",
    label: "Formal & Analytical",
    categories: new Set([
      "core_advanced",
      "abstract_philosophy",
      "abstract_concepts_expanded",
      "meta_language",
      "advanced_grammar_meta_expanded",
      "scientific_analytical",
      "science_research_expanded",
      "philosophy_intellectual_expanded",
      "high_level_discourse_expanded",
    ]),
  },
];

bootstrapData.DOMAIN_BY_CATEGORY = bootstrapData.DOMAIN_BY_CATEGORY || bootstrapData.buildDomainByCategoryMap(bootstrapData.PERFORMANCE_DOMAINS);
bootstrapData.FALLBACK_DOMAIN_ID = bootstrapData.FALLBACK_DOMAIN_ID || bootstrapData.PERFORMANCE_DOMAINS[bootstrapData.PERFORMANCE_DOMAINS.length - 1]?.id || "formal";
})(typeof window !== "undefined" ? window : globalThis);
